import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, readFile, rename, unlink, stat, lstat, realpath, open } from 'node:fs/promises';
import { isAbsolute, join, resolve, relative, sep } from 'node:path';
import { spawn } from 'node:child_process';
import { Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { BlockList, isIP } from 'node:net';
import { lookup as dnsLookup } from 'node:dns/promises';
import { Agent, fetch as undiciFetch } from 'undici';

// Private filesystem adapter. Never mount root as static content. Only the parent
// application's authenticated/entitled route may serve master/source/stem files.
// Neither this module nor retrying ingest can submit a generation request.
const locks = new Map();
const ID = /^[a-f0-9]{64}$/;
const FORMATS = 'wav,mp3,flac,ogg,mov,aac';
const CODES = {
  INVALID_JOB: 'The media job identifier is invalid.',
  INVALID_RESULT: 'The upstream result does not contain a valid delivery envelope.',
  RESULT_CONFLICT: 'This job is already associated with different media objects.',
  INVALID_SOURCE: 'The source is not an allowed Cloud Storage object.',
  UNSAFE_DELIVERY: 'The delivery URL does not match the approved source object.',
  DELIVERY_FAILED: 'A fresh delivery link could not be obtained.',
  DELIVERY_TIMEOUT: 'The delivery link request timed out.',
  DOWNLOAD_FAILED: 'The source audio could not be downloaded.',
  DOWNLOAD_TIMEOUT: 'The audio download timed out.',
  SOURCE_TOO_LARGE: 'The source exceeds the configured media size limit.',
  SOURCE_EMPTY: 'The source contains no media bytes.',
  INVALID_MEDIA: 'The downloaded object is not supported, valid audio.',
  MISSING_TOOLS: 'FFmpeg and FFprobe must be configured and permitted to run on this server.',
  TOOL_TIMEOUT: 'Audio processing exceeded its time limit.',
  PACKAGING_FAILED: 'The listening rendition could not be validated.',
  STORAGE_UNSAFE: 'The media storage location failed its safety check.',
  STORAGE_FAILED: 'The private media record could not be stored.',
  RAW_ONLY: 'The upstream delivered a raw take after a render failure.',
  NO_MASTER: 'No explicitly delivered master is available for this take.',
  NOT_GENERATED: 'This requested take was not generated by the upstream service.',
  STEM_UNAVAILABLE: 'An explicitly requested separate output is unavailable upstream.',
};

export class MediaError extends Error {
  constructor(code, retryable = false) { super(CODES[code] || CODES.STORAGE_FAILED); this.name = 'MediaError'; this.code = code; this.retryable = retryable; }
}
const fail = (code, retryable = false) => { throw new MediaError(code, retryable); };
const digest = value => createHash('sha256').update(value).digest('hex');
const clone = value => JSON.parse(JSON.stringify(value));
const publicError = error => ({ code: error instanceof MediaError ? error.code : 'STORAGE_FAILED', message: error instanceof MediaError ? error.message : CODES.STORAGE_FAILED, retryable: error instanceof MediaError ? error.retryable : true });
const number = (value, fallback) => Number.isFinite(Number(value)) ? Number(value) : fallback;

// Windows indexing/security scanners may briefly hold an otherwise closed file.
// Retry only atomic replacement, never delete the last durable destination.
export async function replaceMediaManifest(source, destination, { renameFile = rename, platform = process.platform, retryWindowMs = 1000 } = {}) {
  const deadline = performance.now() + (Number.isFinite(retryWindowMs) ? Math.min(1000, Math.max(0, retryWindowMs)) : 1000);
  let delay = 10;
  while (true) {
    try { await renameFile(source, destination); return; }
    catch (error) {
      const remaining = deadline - performance.now();
      if (platform !== 'win32' || !['EPERM', 'EACCES', 'EBUSY'].includes(error.code) || remaining <= 0) throw error;
      await new Promise(accept => setTimeout(accept, Math.min(delay, remaining)));
      if (performance.now() >= deadline) throw error;
      delay = Math.min(delay * 2, 100);
    }
  }
}

export function validateGcsUri(value, allowedBuckets) {
  if (typeof value !== 'string' || value.length > 4096) fail('INVALID_SOURCE');
  const match = /^gs:\/\/([a-z0-9][a-z0-9._-]{1,61}[a-z0-9])\/(.+)$/.exec(value);
  const allowed = allowedBuckets instanceof Set ? allowedBuckets : new Set(allowedBuckets || []);
  if (!match || !allowed.has(match[1]) || /[\x00-\x20\\?#]/.test(match[2]) || /(^|\/)\.{1,2}(\/|$)/.test(match[2])) fail('INVALID_SOURCE');
  return { bucket: match[1], object: match[2], uri: value };
}

export function validateDeliveryUrl(value, gcsUri, allowedBuckets, now = Date.now()) {
  const source = validateGcsUri(gcsUri, allowedBuckets);
  if (typeof value !== 'string' || value.length > 16384) fail('UNSAFE_DELIVERY');
  let url; try { url = new URL(value); } catch { fail('UNSAFE_DELIVERY'); }
  if (url.protocol !== 'https:' || url.username || url.password || url.port || url.hash) fail('UNSAFE_DELIVERY');
  const pathStyle = url.hostname === 'storage.googleapis.com';
  if (!pathStyle && url.hostname !== `${source.bucket}.storage.googleapis.com`) fail('UNSAFE_DELIVERY');
  let decoded; try { decoded = decodeURIComponent(url.pathname); } catch { fail('UNSAFE_DELIVERY'); }
  if (decoded !== `/${pathStyle ? `${source.bucket}/` : ''}${source.object}`) fail('UNSAFE_DELIVERY');
  for (const key of ['X-Goog-Algorithm', 'X-Goog-Credential', 'X-Goog-Date', 'X-Goog-Expires', 'X-Goog-SignedHeaders', 'X-Goog-Signature']) {
    if (url.searchParams.getAll(key).length !== 1) fail('UNSAFE_DELIVERY');
  }
  const q = url.searchParams;
  const stamp = q.get('X-Goog-Date');
  const ttl = Number(q.get('X-Goog-Expires'));
  if (q.get('X-Goog-Algorithm') !== 'GOOG4-RSA-SHA256' || q.get('X-Goog-SignedHeaders') !== 'host' || !q.get('X-Goog-Credential') || !/^[a-f0-9]{256,1024}$/i.test(q.get('X-Goog-Signature')) || !/^\d{8}T\d{6}Z$/.test(stamp) || !Number.isInteger(ttl) || ttl < 1 || ttl > 604800) fail('UNSAFE_DELIVERY');
  const date = Date.parse(`${stamp.slice(0,4)}-${stamp.slice(4,6)}-${stamp.slice(6,8)}T${stamp.slice(9,11)}:${stamp.slice(11,13)}:${stamp.slice(13,15)}Z`);
  if (!Number.isFinite(date) || date > now + 300000 || date + ttl * 1000 <= now) fail('UNSAFE_DELIVERY');
  return url;
}

// Operator-only CDN mappings. These do not authorize arbitrary URLs supplied by
// a browser or returned in an upstream error. Every URL must map to its own GCS
// object; the trusted origin alone is insufficient.
export function validateCdnMappings(input = [], allowedBuckets = []) {
  if (!Array.isArray(input) || input.length > 16) throw new TypeError('Configure at most 16 exact media CDN mappings.');
  const buckets = new Set(allowedBuckets), mappings = [];
  const prefix = (value, leading) => typeof value === 'string' && value.length <= 512 && (leading ? value === '/' || /^\/(?:[A-Za-z0-9_.-]+\/)+$/.test(value) : value === '' || /^(?:[A-Za-z0-9_.-]+\/)+$/.test(value)) && !value.split('/').some(part => part === '.' || part === '..');
  for (const entry of input) {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry) || Object.keys(entry).sort().join(',') !== 'bucket,objectPrefix,origin,pathPrefix') throw new TypeError('A CDN mapping requires only origin, bucket, objectPrefix and pathPrefix.');
    const { origin, bucket, objectPrefix, pathPrefix } = entry;
    let url; try { url = new URL(origin); } catch { throw new TypeError('Invalid media CDN origin.'); }
    if (typeof origin !== 'string' || origin.length > 512 || url.origin !== origin || url.protocol !== 'https:' || url.username || url.password || url.port || url.search || url.hash || url.pathname !== '/' || isIP(url.hostname) || !/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(url.hostname) || /\.(?:localhost|local|internal|lan|home|arpa)$/.test(url.hostname)) throw new TypeError('A media CDN requires an exact public HTTPS origin without ports or credentials.');
    if (!buckets.has(bucket) || !prefix(objectPrefix,false) || !prefix(pathPrefix,true)) throw new TypeError('A media CDN must map an approved bucket and canonical object/path prefixes.');
    if (mappings.some(row => row.origin === origin && (row.pathPrefix.startsWith(pathPrefix) || pathPrefix.startsWith(row.pathPrefix) || row.bucket === bucket && (row.objectPrefix.startsWith(objectPrefix) || objectPrefix.startsWith(row.objectPrefix))))) throw new TypeError('Media CDN mappings on one origin must not overlap.');
    mappings.push(Object.freeze({origin,bucket,objectPrefix,pathPrefix}));
  }
  return Object.freeze(mappings);
}

export function validateCdnDeliveryUrl(value, gcsUri, allowedBuckets, mappings = []) {
  const source = validateGcsUri(gcsUri,allowedBuckets);
  if (typeof value !== 'string' || value.length > 16384 || /[\x00-\x20\\]/.test(value)) fail('UNSAFE_DELIVERY');
  let url; try { url = new URL(value); } catch { fail('UNSAFE_DELIVERY'); }
  // Exact canonical comparison also rejects explicit :443 and empty ?/# suffixes.
  if (url.protocol !== 'https:' || url.username || url.password || url.port || url.search || url.hash || url.href !== value) fail('UNSAFE_DELIVERY');
  const permitted = validateCdnMappings(mappings,allowedBuckets).filter(row => row.origin === url.origin && row.bucket === source.bucket && source.object.startsWith(row.objectPrefix));
  if (permitted.length !== 1) fail('UNSAFE_DELIVERY');
  const mapping = permitted[0], remainder = source.object.slice(mapping.objectPrefix.length);
  const pieces = remainder.split('/');
  // Percent-containing object names can have different meanings after a CDN's
  // rewrite/decode layer. They require a separately specified mapping contract.
  if (pieces.some(part => !part || part === '.' || part === '..' || part.includes('%'))) fail('UNSAFE_DELIVERY');
  const encode = part => encodeURIComponent(part).replace(/[!'()*]/g, char => `%${char.charCodeAt(0).toString(16).toUpperCase()}`);
  const expected = mapping.origin + mapping.pathPrefix + pieces.map(encode).join('/');
  if (value !== expected) fail('UNSAFE_DELIVERY');
  return url;
}

// Conservatively exclude IANA special-purpose space (registry checked 2026-09-14),
// multicast/reserved IPv4, and IPv6 outside global unicast. No DNS precheck followed
// by a second lookup: the connector receives only this lookup's vetted answers.
const blockedV4 = new BlockList(), blockedV6 = new BlockList(), globalV6 = new BlockList();
for (const [base,prefix] of [['0.0.0.0',8],['10.0.0.0',8],['100.64.0.0',10],['127.0.0.0',8],['169.254.0.0',16],['172.16.0.0',12],['192.0.0.0',24],['192.0.2.0',24],['192.88.99.0',24],['192.168.0.0',16],['198.18.0.0',15],['198.51.100.0',24],['203.0.113.0',24],['224.0.0.0',4],['240.0.0.0',4]]) blockedV4.addSubnet(base,prefix,'ipv4');
globalV6.addSubnet('2000::',3,'ipv6');
for (const [base,prefix] of [['2001::',23],['2001:db8::',32],['2002::',16],['3fff::',20]]) blockedV6.addSubnet(base,prefix,'ipv6');
export function isPublicMediaAddress(address) {
  if (typeof address !== 'string' || address.includes('%')) return false;
  const family = isIP(address);
  return family === 4 ? !blockedV4.check(address,'ipv4') : family === 6 && globalV6.check(address,'ipv6') && !blockedV6.check(address,'ipv6');
}
export function createCdnLookup(hostname, lookupImpl = dnsLookup) {
  if (typeof hostname !== 'string' || typeof lookupImpl !== 'function') throw new TypeError('An exact CDN hostname and lookup function are required.');
  return (host, options, callback) => {
    if (host !== hostname) { callback(new MediaError('UNSAFE_DELIVERY')); return; }
    Promise.resolve().then(() => lookupImpl(host,{all:true,verbatim:true})).then(records => {
      if (!Array.isArray(records) || !records.length || records.length > 64 || records.some(row => !row || !isPublicMediaAddress(row.address) || isIP(row.address) !== row.family)) fail('UNSAFE_DELIVERY');
      const selected = records.filter(row => !options.family || row.family === options.family).map(row => ({address:row.address,family:row.family}));
      if (!selected.length) fail('UNSAFE_DELIVERY');
      if (options.all) callback(null,selected); else callback(null,selected[0].address,selected[0].family);
    }).catch(error => callback(error instanceof MediaError ? error : new MediaError('DOWNLOAD_FAILED',true)));
  };
}

function safeMetadata(value) {
  if (Array.isArray(value)) return value.map(safeMetadata);
  if (!value || typeof value !== 'object') return value;
  // Lease URLs and transport account identity are not needed for durable media
  // metadata. The parent stores the full generation envelope privately.
  return Object.fromEntries(Object.entries(value).filter(([key]) => !/(?:^auth$|url$|url_signer$|signer$)/i.test(key)).map(([key, item]) => [key, safeMetadata(item)]));
}

function takePlan(result) {
  if (!result || typeof result !== 'object' || Array.isArray(result) || Buffer.byteLength(JSON.stringify(result)) > 4 * 1024 * 1024) fail('INVALID_RESULT');
  const tracks = result.tracks ?? [];
  const sources = result.source_take ?? [];
  if (!Array.isArray(tracks) || !Array.isArray(sources) || tracks.length > 32 || sources.length > 32) fail('INVALID_RESULT');
  const rows = new Map();
  const row = take => { if (!Number.isInteger(take) || take < 1 || take > 32) fail('INVALID_RESULT'); if (!rows.has(take)) rows.set(take, { take, track: null, source: null }); return rows.get(take); };
  tracks.forEach((track, i) => { if (!track || typeof track !== 'object') fail('INVALID_RESULT'); const item = row(track.take ?? i + 1); if (item.track) fail('INVALID_RESULT'); item.track = track; });
  sources.forEach((source, i) => { if (!source || typeof source !== 'object') fail('INVALID_RESULT'); const item = row(source.take ?? i + 1); if (item.source) fail('INVALID_RESULT'); item.source = source; });
  if (result.render_plan?.processed_gcs_uri) row(1);
  const highestTake = rows.size ? Math.max(...rows.keys()) : 0;
  const requested = result.takes_requested ?? result.generation_shortfall?.takes_requested ?? highestTake;
  if (!Number.isInteger(requested) || requested < highestTake || requested > 32) fail('INVALID_RESULT');
  for (let take = 1; take <= requested; take++) row(take);
  if (!rows.size) fail('INVALID_RESULT');
  return [...rows.values()].sort((a, b) => a.take - b.take).map(item => {
    const plan = item.track?.render_plan ?? (item.take === 1 ? result.render_plan : null);
    const raw = /raw\s+take|render\s+pass\s+failed/i.test(item.track?.kind || '');
    const explicitMaster = /^delivered master(?:\b|$)/i.test(item.track?.kind || '');
    const processed = item.take === 1 ? result.render_plan?.processed_gcs_uri : null;
    // Do not let an explicit current raw/failure label become an old-envelope fallback.
    const masterUri = !raw && result.success !== false ? (explicitMaster ? item.track.gcs_uri : processed || null) : null;
    const rawUri = item.source?.gcs_uri || (raw || !masterUri ? item.track?.gcs_uri : null) || null;
    const stemRecords = plan?.stages?.stems?.stems || {};
    if (typeof stemRecords !== 'object' || Array.isArray(stemRecords) || Object.keys(stemRecords).length > 32) fail('INVALID_RESULT');
    const stems = Object.entries(stemRecords).map(([name, record]) => ({ name, record }));
    return { ...item, plan, raw, masterUri, rawUri, stems };
  });
}

async function boundedCall(fn, milliseconds, code) {
  let timer; try { return await Promise.race([Promise.resolve().then(fn), new Promise((_, reject) => { timer = setTimeout(() => reject(new MediaError(code, true)), milliseconds); })]); } finally { clearTimeout(timer); }
}

async function run(binary, args, timeoutMs, failureCode) {
  if (!binary || !isAbsolute(binary)) fail('MISSING_TOOLS');
  return new Promise((accept, reject) => {
    let child;
    try { child = spawn(binary, args, { shell: false, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] }); }
    catch { reject(new MediaError('MISSING_TOOLS')); return; }
    let stdout = '', count = 0, timedOut = false, tooMuch = false;
    const timer = setTimeout(() => { timedOut = true; child.kill('SIGKILL'); }, timeoutMs);
    child.stdout.on('data', data => { count += data.length; if (count > 1024 * 1024) { tooMuch = true; child.kill('SIGKILL'); } else stdout += data.toString('utf8'); });
    child.stderr.on('data', data => { count += data.length; if (count > 1024 * 1024) { tooMuch = true; child.kill('SIGKILL'); } });
    child.once('error', () => { clearTimeout(timer); reject(new MediaError('MISSING_TOOLS')); });
    child.once('close', code => { clearTimeout(timer); if (timedOut) reject(new MediaError('TOOL_TIMEOUT', true)); else if (code !== 0 || tooMuch) reject(new MediaError(failureCode)); else accept(stdout); });
  });
}

export function createMedia({ root, delivery, ffmpegPath, ffprobePath, allowedBuckets = [], mediaCdnMappings = [], fetchImpl = globalThis.fetch, cdnLookupImpl = dnsLookup, maxBytes = 256 * 1024 * 1024, maxDurationSeconds = 900, downloadTimeoutMs = 120000, deliveryTimeoutMs = 15000, processTimeoutMs = 120000 } = {}) {
  if (!root || !isAbsolute(root) || typeof delivery !== 'function' || typeof fetchImpl !== 'function' || !allowedBuckets.length || !Number.isSafeInteger(maxBytes) || maxBytes < 1 || !Number.isFinite(maxDurationSeconds) || maxDurationSeconds <= 0) throw new TypeError('An absolute private root, delivery callback, allowed buckets and bounded media limits are required.');
  if (![downloadTimeoutMs, deliveryTimeoutMs, processTimeoutMs].every(value => Number.isInteger(value) && value > 0 && value <= 600000)) throw new TypeError('Media time limits must be positive integer milliseconds, at most ten minutes.');
  const storageRoot = resolve(root);
  if (storageRoot.split(/[\\/]/).some(part => part.toLowerCase() === 'public')) fail('STORAGE_UNSAFE');
  const buckets = new Set(allowedBuckets);
  const cdnMappings = validateCdnMappings(mediaCdnMappings,allowedBuckets);
  if (typeof cdnLookupImpl !== 'function') throw new TypeError('The media DNS lookup must be a function.');
  const ready = (async () => {
    await mkdir(storageRoot, { recursive: true, mode: 0o700 });
    if ((await lstat(storageRoot)).isSymbolicLink()) fail('STORAGE_UNSAFE');
    return realpath(storageRoot);
  })();
  const contained = async (path, mustExist = false) => {
    const canonicalRoot = await ready;
    const rel = relative(storageRoot, resolve(path));
    if (rel.startsWith(`..${sep}`) || rel === '..' || isAbsolute(rel)) fail('STORAGE_UNSAFE');
    const components = rel ? rel.split(sep) : [];
    let cursor = canonicalRoot;
    for (const part of components) {
      cursor = join(cursor, part);
      try { if ((await lstat(cursor)).isSymbolicLink()) fail('STORAGE_UNSAFE'); } catch (error) { if (error.code === 'ENOENT' && !mustExist) break; throw error; }
    }
    return path;
  };
  const directory = async path => { await contained(path); await mkdir(path, { recursive: true, mode: 0o700 }); await contained(path, true); };
  const atomicJson = async (path, value) => {
    await contained(path); const tmp = `${path}.${randomUUID()}.tmp`;
    try { const handle = await open(tmp, 'wx', 0o600); try { await handle.writeFile(JSON.stringify(value)); await handle.sync(); } finally { await handle.close(); } await replaceMediaManifest(tmp, path); } finally { await unlink(tmp).catch(() => {}); }
  };
  const readJson = async path => { await contained(path, true); const info = await stat(path); if (!info.isFile() || info.size > 8 * 1024 * 1024) fail('STORAGE_UNSAFE'); return JSON.parse(await readFile(path, 'utf8')); };
  const jobKey = jobId => { if (typeof jobId !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(jobId)) fail('INVALID_JOB'); return digest(`job:${jobId}`); };
  const jobPath = jobId => join(storageRoot, 'jobs', `${jobKey(jobId)}.json`);
  const assetDirectory = id => { if (!ID.test(id)) fail('STORAGE_UNSAFE'); return join(storageRoot, 'objects', id); };

  async function probe(path) {
    const raw = await run(ffprobePath, ['-v', 'error', '-protocol_whitelist', 'file', '-format_whitelist', FORMATS, '-show_entries', 'format=duration,format_name:stream=codec_type,codec_name,sample_rate,channels,duration', '-of', 'json', path], processTimeoutMs, 'INVALID_MEDIA');
    let data; try { data = JSON.parse(raw); } catch { fail('INVALID_MEDIA'); }
    const streams = data.streams || [];
    const audio = streams.filter(stream => stream.codec_type === 'audio');
    const duration = number(data.format?.duration, number(audio[0]?.duration, NaN));
    const sampleRate = Number(audio[0]?.sample_rate), channels = Number(audio[0]?.channels);
    if (audio.length !== 1 || streams.length !== 1 || !Number.isFinite(duration) || duration <= 0 || duration > maxDurationSeconds || !Number.isInteger(sampleRate) || sampleRate < 8000 || sampleRate > 192000 || !Number.isInteger(channels) || channels < 1 || channels > 8 || !/^(?:pcm_[a-z0-9]+|mp3|aac|flac|opus|vorbis)$/.test(audio[0].codec_name || '')) fail('INVALID_MEDIA');
    return { measured: true, measuredBy: 'ffprobe on owner-stored bytes', durationSeconds: duration, codec: audio[0].codec_name, sampleRate, channels, format: data.format.format_name };
  }
  async function fileDigest(path) {
    await contained(path, true); const hash = createHash('sha256'); let size = 0;
    for await (const chunk of createReadStream(path)) { size += chunk.length; if (size > maxBytes) fail('SOURCE_TOO_LARGE'); hash.update(chunk); }
    return { sha256: hash.digest('hex'), size };
  }
  async function validExisting(id, kind) {
    const folder = assetDirectory(id);
    try {
      const record = await readJson(join(folder, 'asset.json'));
      if (record.kind !== kind) return null;
      if (record.id !== id || record.file !== (kind === 'listening' ? 'audio.mp3' : 'audio.bin')) fail('STORAGE_UNSAFE');
      const path = join(folder, record.file); const bytes = await fileDigest(path);
      if (bytes.size !== record.size || bytes.sha256 !== record.sha256) return null;
      return { ...record, path };
    } catch (error) { if (error.code === 'ENOENT' || error instanceof SyntaxError) return null; throw error; }
  }
  async function download(gcsUri, tmp) {
    validateGcsUri(gcsUri, buckets);
    for (let attempt = 0; attempt < 2; attempt++) {
      let lease; try { lease = await boundedCall(() => delivery(gcsUri), deliveryTimeoutMs, 'DELIVERY_TIMEOUT'); } catch (error) { if (error instanceof MediaError) throw error; fail('DELIVERY_FAILED', true); }
      if (!lease || lease.success === false || (lease.gcs_uri && lease.gcs_uri !== gcsUri)) fail('UNSAFE_DELIVERY');
      const isCdn = lease.url_kind === 'cdn_unsigned';
      if (lease.url_kind !== undefined && !['v4_signed','cdn_unsigned'].includes(lease.url_kind)) fail('UNSAFE_DELIVERY');
      if (isCdn && lease.url_expires_at !== null && lease.url_expires_at !== undefined) fail('UNSAFE_DELIVERY');
      const url = isCdn ? validateCdnDeliveryUrl(lease.url,gcsUri,buckets,cdnMappings) : validateDeliveryUrl(lease.url,gcsUri,buckets);
      const dispatcher = isCdn ? new Agent({connect:{lookup:createCdnLookup(url.hostname,cdnLookupImpl),timeout:Math.min(downloadTimeoutMs,10000)},maxRedirections:0}) : null;
      const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), downloadTimeoutMs);
      try {
        const transport = isCdn && fetchImpl === globalThis.fetch ? undiciFetch : fetchImpl;
        const response = await transport(url.href, { method: 'GET', redirect: 'manual', signal: controller.signal, headers: { 'Accept-Encoding': 'identity' },...(dispatcher?{dispatcher}:{}) });
        if (!isCdn && (response.status === 401 || response.status === 403) && attempt === 0) { await response.body?.cancel(); continue; }
        if (response.status !== 200 || response.redirected || !response.body) { await response.body?.cancel(); fail('DOWNLOAD_FAILED', response.status >= 500 || response.status === 403); }
        if (response.headers.get('content-encoding') && response.headers.get('content-encoding') !== 'identity') { await response.body.cancel(); fail('INVALID_MEDIA'); }
        const declared = response.headers.get('content-length');
        if (declared !== null && (!/^\d+$/.test(declared) || Number(declared) > maxBytes)) { await response.body.cancel(); fail('SOURCE_TOO_LARGE'); }
        let size = 0; const hash = createHash('sha256');
        const meter = new Transform({ transform(chunk, _, callback) { size += chunk.length; if (size > maxBytes) callback(new MediaError('SOURCE_TOO_LARGE')); else { hash.update(chunk); callback(null, chunk); } } });
        await pipeline(Readable.fromWeb(response.body), meter, createWriteStream(tmp, { flags: 'wx', mode: 0o600 }), { signal: controller.signal });
        if (!size) fail('SOURCE_EMPTY');
        if (declared !== null && Number(declared) !== size) fail('DOWNLOAD_FAILED', true);
        const handle = await open(tmp, 'r+'); try { await handle.sync(); } finally { await handle.close(); }
        return { size, sha256: hash.digest('hex') };
      } catch (error) { if (controller.signal.aborted) fail('DOWNLOAD_TIMEOUT', true); if (error instanceof MediaError) throw error; if(error?.cause instanceof MediaError)throw error.cause; fail('DOWNLOAD_FAILED', true); } finally { clearTimeout(timer); if(dispatcher)await dispatcher.destroy(); }
    }
    fail('DOWNLOAD_FAILED', true);
  }
  async function storeObject(jobId, take, kind, sourceUri, label = '') {
    validateGcsUri(sourceUri, buckets);
    const id = digest(JSON.stringify(['owned-media-v1', jobId, take, kind, label, sourceUri]));
    const existing = await validExisting(id, kind); if (existing) return existing;
    const folder = assetDirectory(id); await directory(folder);
    const tmp = join(folder, `${randomUUID()}.part`);
    try {
      const bytes = await download(sourceUri, tmp);
      const measured = await probe(tmp);
      const format = measured.format.split(',')[0];
      const extension = ({ wav: 'wav', mp3: 'mp3', flac: 'flac', ogg: 'ogg', mov: 'm4a', aac: 'aac' })[format];
      if (!extension) fail('INVALID_MEDIA');
      const record = { id, jobId, take, kind, label, sourceUri, file: 'audio.bin', extension, downloadName: `take-${take}.${extension}`, ...bytes, ...measured, contentType: ({ wav: 'audio/wav', mp3: 'audio/mpeg', flac: 'audio/flac', ogg: 'audio/ogg', m4a: 'audio/mp4', aac: 'audio/aac' })[extension], createdAt: new Date().toISOString() };
      const path = join(folder, record.file); await contained(path); await rename(tmp, path); await atomicJson(join(folder, 'asset.json'), record);
      return { ...record, path };
    } finally { await unlink(tmp).catch(() => {}); }
  }
  async function listening(master) {
    const id = digest(JSON.stringify(['listening-mp3-192k-v1', master.id, master.sha256]));
    const existing = await validExisting(id, 'listening'); if (existing) return existing;
    const folder = assetDirectory(id); await directory(folder); const tmp = join(folder, `${randomUUID()}.part`);
    try {
      await run(ffmpegPath, ['-hide_banner', '-loglevel', 'error', '-nostdin', '-xerror', '-threads', '2', '-protocol_whitelist', 'file', '-format_whitelist', FORMATS, '-i', master.path, '-map', '0:a:0', '-vn', '-sn', '-dn', '-map_metadata', '-1', '-map_chapters', '-1', '-c:a', 'libmp3lame', '-b:a', '192k', '-ar', String(master.sampleRate === 44100 ? 44100 : 48000), '-ac', String(Math.min(master.channels, 2)), '-threads', '2', '-t', String(maxDurationSeconds + 1), '-f', 'mp3', '-n', tmp], processTimeoutMs, 'PACKAGING_FAILED');
      const bytes = await fileDigest(tmp), measured = await probe(tmp);
      if (!bytes.size || measured.codec !== 'mp3' || Math.abs(measured.durationSeconds - master.durationSeconds) > 0.25) fail('PACKAGING_FAILED');
      const record = { id, jobId: master.jobId, take: master.take, kind: 'listening', parentId: master.id, file: 'audio.mp3', ...bytes, ...measured, contentType: 'audio/mpeg', profile: 'mp3-192k-v1', createdAt: new Date().toISOString() };
      const path = join(folder, record.file); await contained(path); await rename(tmp, path); await atomicJson(join(folder, 'asset.json'), record);
      return { ...record, path };
    } finally { await unlink(tmp).catch(() => {}); }
  }

  async function ingestLocked(jobId, result) {
    const planned = takePlan(result);
    const fingerprint = digest(JSON.stringify(planned.map(item => [item.take, item.masterUri, item.rawUri, item.stems.map(stem => [stem.name, stem.record?.state, stem.record?.gcs_uri])])));
    let previous; try { previous = await read(jobId); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (previous && previous.fingerprint !== fingerprint) fail('RESULT_CONFLICT');
    const manifest = { version: 1, jobId, fingerprint, status: 'ingesting', takes: [], generationShortfall: safeMetadata(result.generation_shortfall ?? null), upstreamSuccess: result.success === true, upstream: safeMetadata(result), updatedAt: new Date().toISOString() };
    await directory(join(storageRoot, 'jobs'));
    await atomicJson(jobPath(jobId), manifest);
    for (const item of planned) {
      const take = { take: item.take, id: digest(JSON.stringify(['take', jobId, item.take])), status: 'failed', kind: item.raw ? 'raw' : item.masterUri ? 'delivered-master' : 'unavailable', master: null, listening: null, source: null, stems: [], errors: [], upstream: safeMetadata(item.track ?? item.source ?? {}) };
      if (item.masterUri) {
        try { take.master = await storeObject(jobId, item.take, 'master', item.masterUri); take.listening = await listening(take.master); } catch (error) { take.errors.push(publicError(error)); }
      } else take.errors.push(publicError(new MediaError(item.raw ? 'RAW_ONLY' : !item.track && !item.source ? 'NOT_GENERATED' : 'NO_MASTER')));
      if (item.rawUri) { try { take.source = await storeObject(jobId, item.take, 'source', item.rawUri); } catch (error) { take.errors.push(publicError(error)); } }
      for (const stem of item.stems) {
        const record = { name: stem.name, upstream: safeMetadata(stem.record), asset: null };
        if (stem.record?.state === 'DELIVERED') { try { record.asset = await storeObject(jobId, item.take, 'stem', stem.record.gcs_uri, stem.name); } catch (error) { record.error = publicError(error); take.errors.push(record.error); } }
        else { record.error = { ...publicError(new MediaError('STEM_UNAVAILABLE')), upstreamState: stem.record?.state ?? null, stem: stem.name }; take.errors.push(record.error); }
        take.stems.push(record);
      }
      take.status = take.listening ? (take.errors.length ? 'partial' : 'ready') : 'failed';
      manifest.takes.push(take); manifest.updatedAt = new Date().toISOString(); await atomicJson(jobPath(jobId), manifest);
    }
    manifest.status = manifest.takes.every(take => take.status === 'ready') && !manifest.generationShortfall && manifest.upstreamSuccess ? 'ready' : manifest.takes.some(take => take.listening || take.source || take.master) ? 'partial' : 'failed';
    manifest.updatedAt = new Date().toISOString(); await atomicJson(jobPath(jobId), manifest); return clone(manifest);
  }
  async function ingest(jobId, result) {
    // One Node process serializes each job across adapter instances. The parent
    // durable job owner must enforce exclusive claims across worker processes.
    const key = `${storageRoot}:${jobKey(jobId)}`;
    const previous = locks.get(key) || Promise.resolve();
    const next = previous.catch(() => {}).then(() => ingestLocked(jobId, result));
    locks.set(key, next); try { return await next; } finally { if (locks.get(key) === next) locks.delete(key); }
  }
  async function read(jobId) { return readJson(jobPath(jobId)); }
  async function resolveAsset(id, kind = 'listening') {
    if (!ID.test(id) || !['listening', 'master', 'source', 'stem'].includes(kind)) return null;
    return validExisting(id, kind);
  }
  async function health() {
    try { await ready; const [ffmpeg, ffprobe] = await Promise.all([run(ffmpegPath, ['-version'], 5000, 'MISSING_TOOLS'), run(ffprobePath, ['-version'], 5000, 'MISSING_TOOLS')]); return { configured: true, ffmpeg: ffmpeg.split('\n')[0], ffprobe: ffprobe.split('\n')[0] }; } catch (error) { return { configured: false, error: publicError(error) }; }
  }
  return Object.freeze({ ingest, read, resolve: resolveAsset, health });
}
