"""English grapheme-to-phoneme for the PER gate — LEXICON tier + MEASURED variant-rule tier.

NOTE FOR OTHER AGENTS (read before editing):
- This module mirrors the `g2p_tr` interface EXACTLY (WordPhonemes / normalise / words /
  word_to_phonemes / text_to_phonemes / fold_for_scoring / load_lexicon) because
  `per_gate` dispatches on language and depends on that contract. Change one, change both,
  and the control suites (`scripts/test_g2p_en.py`, `scripts/test_per_gate.py`) must stay green.
- EVERY rule here is a MEASURED distribution, not a textbook recollection: the rule evidence
  lives in `data/g2p_en.json`, which is GENERATED by `scripts/build_g2p_en_rules.py` from
  `scripts/measure_en_variant_rules_from_lexicon.py`'s pair measurement over the shipped MFA
  en_US dictionary (61,061 words, CC BY 4.0). Hand-editing the data file is forbidden — re-run
  the measurement instead (supreme-law LINK 10: agreement by import, never by discipline).
- A word neither in the lexicon nor resolvable by a measured rule is returned with
  tier="unresolved" and NO phonemes. GUESSING A PRONUNCIATION IS FORBIDDEN (Mandate CLAUSE 4);
  the PER gate must surface the word, never a fabricated reference. Measured on vocadito EN
  (2026-08-17): lexicon alone covers 96.29 % of tokens; the rules resolve 8 of the 11 OOV
  types; 3 nursery-rhyme types (itsy, bitsy, waggedy) remain honestly unresolved.

THE TIER ORDER:
  TIER 1 — LEXICON. `data/lexicon/english_us_mfa.dict` (first pronunciation primary, the rest
    variants — the same convention `g2p_tr` uses for `turkish_mfa.dict`).
  TIER 2 — MEASURED VARIANT RULES, applied ONLY when the base form is itself a lexicon hit:
    g-dropping (-in' -> -ing, final ŋ -> n: the dictionary's own 45 'ɪ n' -ing entries prove the
    realization), clitics ('s, 'll), inflection suffixes (-s, -ed) whose appended phone material
    is the MAJORITY of the lexicon's own (base, base+suffix) pairs conditioned on the base-final
    phone, and the reduced-form map ('cause -> because).
  TIER 3 — NONE. There is deliberately no neural fallback and no letter-to-sound guesser:
    English orthography is deep (unlike Turkish), so an unsourced rule tier would be the
    guessed-parameter class this project bans. Absence is REPORTED per word.
"""

from __future__ import annotations

import io
import json
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final

_PKG_DIR = Path(__file__).resolve().parent
LEXICON_PATH: Final[Path] = _PKG_DIR / "data" / "lexicon" / "english_us_mfa.dict"
RULES_PATH: Final[Path] = _PKG_DIR / "data" / "g2p_en.json"

#: Punctuation stripped from word edges. The ASCII apostrophe is deliberately NOT here: it is
#: phonologically meaningful in English at both edges ("tryin'" g-dropping, "'cause" reduction).
_EDGE_PUNCTUATION: Final[str] = ".,;:!?\"()[]…—-“”‘’"

#: MFA's non-phone symbols, identical to the Turkish module's set (same dictionary family).
NON_PHONE_SYMBOLS: Final[frozenset[str]] = frozenset({"spn", "sil", "sp", "<eps>", "<unk>"})


@dataclass
class WordPhonemes:
    word: str
    phonemes: list[str]
    tier: str                        # "lexicon" | "variant_rule:<name>" | "unresolved"
    variants: list[list[str]] = field(default_factory=list)


_lexicon: dict[str, list[list[str]]] | None = None
_rules: dict | None = None


def load_lexicon(path: Path | None = None) -> dict[str, list[list[str]]]:
    """word -> list of pronunciation variants, each a list of phone symbols. Loaded once."""
    global _lexicon
    if _lexicon is None:
        target = path or LEXICON_PATH
        if not target.exists():
            raise FileNotFoundError(
                f"the MFA English (US) lexicon is missing at {target}. Tier 1 is MANDATORY: "
                f"English orthography is deep and this module deliberately has no letter-to-sound "
                f"guesser. Fetch the MFA english_us_mfa dictionary (CC BY 4.0) with the corpus "
                f"tooling before using the English PER path.")
        table: dict[str, list[list[str]]] = {}
        with io.open(target, encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\n")
                if not line.strip():
                    continue
                word, _, phones = line.partition("\t")
                # Defensive numeric-column drop, same reason as g2p_tr: the probability-annotated
                # MFA release prefixes numeric fields; a swapped file must not poison the phones.
                parts = [p for p in phones.split() if not _is_number(p)]
                if not parts:
                    continue
                table.setdefault(normalise(word), []).append(parts)
        _lexicon = table
    return _lexicon


def load_rules() -> dict:
    """The measured rule evidence (generated file — see module docstring). Loaded once."""
    global _rules
    if _rules is None:
        if not RULES_PATH.exists():
            raise FileNotFoundError(
                f"the measured English rule file is missing at {RULES_PATH}. It is GENERATED: run "
                f"scripts/measure_en_variant_rules_from_lexicon.py then "
                f"scripts/build_g2p_en_rules.py. Writing it by hand is forbidden.")
        _rules = json.loads(RULES_PATH.read_text(encoding="utf-8"))
    return _rules


def _is_number(token: str) -> bool:
    try:
        float(token)
        return True
    except ValueError:
        return False


def normalise(text: str) -> str:
    """NFC + `.lower()`, plus typographic-apostrophe folding (U+2019 -> ') so lyric files typed
    with smart quotes hit the same lexicon keys. English has no dotted/dotless-I hazard, but every
    metric in the EN path must still reach text through THIS function — single source of truth,
    same law as `g2p_tr.normalise`."""
    text = unicodedata.normalize("NFC", text)
    return text.replace("\u2019", "'").lower()


def words(text: str) -> list[str]:
    """The ONE English word tokenisation: normalised, whitespace-split, edge-punctuation stripped
    (apostrophes preserved — they are phonology here), alphabetic-bearing tokens only."""
    out: list[str] = []
    for token in normalise(text).split():
        token = token.strip(_EDGE_PUNCTUATION)
        if any(c.isalpha() for c in token):
            out.append(token)
    return out


def fold_for_scoring(phonemes: list[str]) -> list[str]:
    """Drop MFA's non-phone symbols. No allophone fold is applied for English because none has
    been MEASURED as necessary (the Turkish fold exists because a 70-vs-65 phone-set mismatch was
    measured between that dictionary and its G2P model; no equivalent mismatch has been measured
    here — if one is, measure first, then extend this function with the evidence)."""
    return [p for p in phonemes if p not in NON_PHONE_SYMBOLS]


def _majority_appended(conditional: dict[str, dict[str, int]], final_phone: str) -> str | None:
    """The majority appended material for a base-final phone, from the measured conditional map.
    Ties break lexicographically — deterministic and documented, never a judgement call."""
    outcomes = conditional.get(final_phone)
    if not outcomes:
        return None
    best_count = max(outcomes.values())
    return sorted(m for m, c in outcomes.items() if c == best_count)[0]


def _variant_rule_word(word: str, table: dict[str, list[list[str]]]) -> WordPhonemes | None:
    """TIER 2: measured variant rules. Returns None when no rule resolves the word — the caller
    reports `unresolved`; nothing here ever guesses."""
    rules = load_rules()

    reduced = rules["reduced_forms"]["map"].get(word)
    if reduced and reduced in table:
        base = table[reduced][0]
        return WordPhonemes(word=word, phonemes=list(base), tier="variant_rule:reduced_form",
                            variants=[list(v) for v in table[reduced][1:]])

    if word.endswith("in'") and len(word) > 3:
        full = word[:-1] + "g"
        hit = table.get(full)
        if hit and hit[0] and hit[0][-1] == "ŋ":
            dropped = list(hit[0][:-1]) + ["n"]
            return WordPhonemes(word=word, phonemes=dropped, tier="variant_rule:g_dropping",
                                variants=[list(hit[0])])

    for suffix, rule_name in (("'s", "clitic_s"), ("'ll", "clitic_ll"),
                              ("s", "suffix_s"), ("ed", "suffix_ed")):
        if not word.endswith(suffix) or len(word) <= len(suffix):
            continue
        base_word = word[: -len(suffix)]
        hit = table.get(base_word)
        if not hit:
            continue
        base = hit[0]
        if suffix == "'ll":
            appended_variants = load_rules()["suffix_rules"]["'ll"]["appended_variants"]
            primary = appended_variants[0].split()
            others = [base + v.split() for v in appended_variants[1:]]
            return WordPhonemes(word=word, phonemes=list(base) + primary,
                                tier=f"variant_rule:{rule_name}", variants=others)
        conditional = rules["suffix_rules"]["s" if suffix == "'s" else suffix][
            "conditional_on_base_final_phone"]
        appended = _majority_appended(conditional, base[-1]) if base else None
        if appended is None:
            return None
        return WordPhonemes(word=word, phonemes=list(base) + appended.split(),
                            tier=f"variant_rule:{rule_name}")
    return None


def word_to_phonemes(word: str, *, lexicon: dict[str, list[list[str]]] | None = None) -> WordPhonemes:
    """TIER 1 then TIER 2, tier always reported. An unresolvable word is returned with
    tier='unresolved' and no phonemes — the gate surfaces it; nobody invents a pronunciation."""
    table = lexicon if lexicon is not None else load_lexicon()
    key = normalise(word).strip(_EDGE_PUNCTUATION)
    hit = table.get(key)
    if hit:
        return WordPhonemes(word=key, phonemes=list(hit[0]), tier="lexicon",
                            variants=[list(v) for v in hit[1:]])
    resolved = _variant_rule_word(key, table)
    if resolved is not None:
        return resolved
    return WordPhonemes(word=key, phonemes=[], tier="unresolved")


def text_to_phonemes(text: str, *, lexicon: dict[str, list[list[str]]] | None = None) -> dict:
    """Phonemise a whole lyric line. Returns the flat sequence AND the per-word tier provenance,
    so a PER number can never be reported without knowing how its reference was derived."""
    table = lexicon if lexicon is not None else load_lexicon()
    per_word = [word_to_phonemes(w, lexicon=table) for w in words(text)]
    flat: list[str] = []
    for entry in per_word:
        flat.extend(entry.phonemes)
    return {
        "text": text,
        "words": [{"word": e.word, "phonemes": e.phonemes, "tier": e.tier,
                   "variants": e.variants} for e in per_word],
        "phonemes": flat,
        "tier_counts": {
            "lexicon": sum(1 for e in per_word if e.tier == "lexicon"),
            "variant_rule": sum(1 for e in per_word if e.tier.startswith("variant_rule")),
            "unresolved": sum(1 for e in per_word if e.tier == "unresolved"),
        },
        "unresolved_words": [e.word for e in per_word if e.tier == "unresolved"],
        "neural_fallback": "NONE BY DESIGN (deep orthography: an unsourced letter-to-sound tier "
                           "would be a guessed parameter; unresolved words are reported instead)",
    }
