const {chromium}=require('../../docs/design/2026-09-09-html-mockups/tools/node_modules/playwright');const fs=require('node:fs'),path=require('node:path');
const out=path.resolve(__dirname,'../verification');const results=[],errors=[];const check=(name,ok,details)=>{results.push({name,pass:!!ok,details});if(!ok)throw Error(name+' failed: '+JSON.stringify(details));};
function tone(name,hz=220,seconds=16){const rate=44100,n=rate*seconds,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++){const t=i/rate,envelope=t<2?0:Math.min(1,(t-2)*4)*(.55+.35*Math.sin(t*4)**2);b.writeInt16LE(Math.round(32767*.28*envelope*(Math.sin(2*Math.PI*hz*t)+.35*Math.sin(2*Math.PI*hz*3*t))),44+i*2);}return{name,mimeType:'audio/wav',buffer:b};}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1504,height:1048},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
try{await page.goto('http://127.0.0.1:4173/player-three.html');await page.evaluate(()=>PMP_PLAYER.ready);await page.waitForFunction(()=>window.PMP_ROOM?.diagnostics.frames>20);check('Actual WebGL renderer and idle silence',await page.evaluate(()=>PMP_ROOM.diagnostics.webgl&&PMP_ROOM.diagnostics.energy===0&&PMP_ROOM.diagnostics.revision==='185'));
await page.screenshot({path:path.join(out,'three-player-desktop.png'),fullPage:true});
await page.locator('#audio-files').setInputFiles([tone('Audio verification — low.wav',110),tone('Audio verification — high.wav',1760)]);await page.waitForFunction(()=>!PMP_PLAYER.state.paused&&PMP_PLAYER.state.queue.length===2);await page.waitForFunction(()=>PMP_PLAYER.state.time>3&&PMP_ROOM.diagnostics.energy>.01);check('Real audio playing with measured spectrum',true,await page.evaluate(()=>({state:PMP_PLAYER.state,scene:PMP_ROOM.diagnostics})));await page.waitForFunction(()=>PMP_PLAYER.state.waveform===320);check('Waveform decoded from actual audio file',true);
await page.locator('#play').click();await page.waitForTimeout(900);check('Pause stops audio and reactive energy settles',await page.evaluate(()=>PMP_PLAYER.state.paused&&PMP_ROOM.diagnostics.energy<.001));
await page.locator('#seek').fill('500');check('Seek changes media time',await page.evaluate(()=>Math.abs(PMP_PLAYER.state.time-8)<.3));
await page.locator('#favorite').click();check('Favorite shared with main library',await page.evaluate(()=>JSON.parse(localStorage.getItem('pmp.saved')).some(t=>t.id===PMP_PLAYER.state.current)));
await page.locator('#volume').fill('0.32');check('Volume control applies',await page.evaluate(()=>PMP_PLAYER.state.volume===.32));await page.locator('#mute').click();check('Mute state applies',await page.evaluate(()=>PMP_PLAYER.state.muted));await page.locator('#mute').click();
await page.locator('#shuffle').click();check('Shuffle enables',await page.evaluate(()=>PMP_PLAYER.state.shuffle));await page.locator('#shuffle').click();await page.locator('#repeat').click();await page.locator('#repeat').click();check('Repeat song mode',await page.evaluate(()=>PMP_PLAYER.state.repeat===2));await page.locator('#repeat').click();
await page.locator('#sound-toggle').click();await page.locator('#eq-preset').selectOption('bass');check('Five-band EQ profile',await page.evaluate(()=>PMP_PLAYER.state.eq.join(',')==='5,3,-1,0,1'));await page.locator('#eq-2').fill('4');check('Custom EQ band and profile',await page.evaluate(()=>PMP_PLAYER.state.eq[2]===4&&document.querySelector('#eq-preset').value==='custom'));await page.locator('#eq-reset').click();await page.locator('#speed').fill('1.2');check('Playback rate and pitch preservation',await page.evaluate(()=>document.querySelector('#audio').playbackRate===1.2&&document.querySelector('#audio').preservesPitch));await page.locator('#loop-a').click();await page.evaluate(()=>document.querySelector('#audio').currentTime=11);await page.locator('#loop-b').click();check('A–B passage loop set',await page.evaluate(()=>Math.abs(PMP_PLAYER.state.loopA-8)<.3&&PMP_PLAYER.state.loopB===11));await page.locator('#loop-clear').click();check('A–B loop clears',await page.evaluate(()=>PMP_PLAYER.state.loopA===null&&PMP_PLAYER.state.loopB===null));await page.locator('#sound-panel .close-panel').click();check('Drawer returns focus',await page.locator('#sound-toggle').evaluate(el=>el===document.activeElement));
await page.locator('#queue-toggle').click();await page.locator('.queue-item').first().locator('[data-action=down]').click();check('Queue reorders real tracks',await page.evaluate(()=>PMP_PLAYER.state.queue[0].title.includes('high')));await page.locator('.queue-item').first().locator('[data-action=select]').click();await page.waitForFunction(()=>!PMP_PLAYER.state.paused&&document.querySelector('#track-title').textContent.includes('high'));await page.locator('#queue-panel .close-panel').click();
for(const form of ['orbit','wave','halo']){await page.locator('#visual-toggle').click();await page.locator('#form').selectOption(form);await page.locator('#visual-panel .close-panel').click();await page.waitForTimeout(350);check('Sculpture mode '+form,await page.evaluate(value=>PMP_ROOM.diagnostics.form===value,form));await page.screenshot({path:path.join(out,`three-player-${form}.png`),fullPage:true});}
for(const world of ['deep','glow','night']){await page.locator(`[data-world=${world}]`).click();check('Atmosphere '+world,await page.evaluate(value=>PMP_PLAYER.state.visual.world===value,world));}
await page.locator('#visual-toggle').click();await page.locator('#quality').selectOption('low');await page.locator('#motion').uncheck();check('Motion and quality settings',await page.evaluate(()=>!PMP_ROOM.diagnostics.motion&&PMP_ROOM.diagnostics.quality==='low'));await page.locator('#motion').check();await page.locator('#quality').selectOption('auto');await page.locator('#visual-panel .close-panel').click();
await page.locator('#cinema').click();check('Cinema expands scene',await page.locator('body').evaluate(el=>el.classList.contains('cinema')));await page.screenshot({path:path.join(out,'three-player-cinema.png'),fullPage:true});await page.keyboard.press('Escape');check('Escape exits cinema',await page.locator('body').evaluate(el=>!el.classList.contains('cinema')));
await page.locator('#fullscreen').click();check('Fullscreen enters',await page.evaluate(()=>!!document.fullscreenElement));await page.locator('#fullscreen').click();check('Fullscreen exits',await page.evaluate(()=>!document.fullscreenElement));
await page.evaluate(()=>document.activeElement.blur());const prior=await page.evaluate(()=>PMP_PLAYER.state.paused);await page.keyboard.press('Space');check('Space shortcut controls playback',await page.evaluate(prior=>PMP_PLAYER.state.paused!==prior,prior));await page.keyboard.press('q');check('Queue keyboard shortcut',await page.locator('#queue-panel').isVisible());await page.keyboard.press('Escape');
await page.reload();await page.evaluate(()=>PMP_PLAYER.ready);check('Real local files and queue order restored without autoplay',await page.evaluate(()=>PMP_PLAYER.state.queue.length===2&&PMP_PLAYER.state.paused&&PMP_PLAYER.state.queue[0].title.includes('high')));await page.locator('#play').click();await page.waitForFunction(()=>!PMP_PLAYER.state.paused);check('Restored Blob audio plays',true);await page.locator('#play').click();
await page.locator('#audio-files').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('not audio')});check('Unsupported file rejected',await page.evaluate(()=>PMP_PLAYER.state.queue.length===2));
await page.locator('#queue-toggle').click();await page.locator('.queue-item').first().locator('[data-action=remove]').click();check('Current queue removal selects remaining track',await page.evaluate(()=>PMP_PLAYER.state.queue.length===1&&PMP_PLAYER.state.current===PMP_PLAYER.state.queue[0].id));await page.locator('#clear-queue').click();check('Clear queue resets all transport state',await page.evaluate(()=>PMP_PLAYER.state.queue.length===0&&!PMP_PLAYER.state.current&&document.querySelector('#seek').disabled));await page.locator('#queue-panel .close-panel').click();
for(const [width,height]of [[320,850],[390,844],[600,960],[820,1180],[1280,800],[1920,1080]]){await page.setViewportSize({width,height});await page.waitForTimeout(350);const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('.transport button,.topbar button,.atmosphere,.rail-btn')].filter(el=>el.getClientRects().length).every(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+.5;})}));check('Responsive layout '+width,metrics.scroll<=width&&metrics.buttons,metrics);await page.screenshot({path:path.join(out,`three-player-${width}.png`),fullPage:true});}
check('No runtime or console errors',errors.length===0,errors);
const reducedPage=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});await reducedPage.goto('http://127.0.0.1:4173/player-three.html');await reducedPage.waitForFunction(()=>window.PMP_ROOM);check('System reduced motion respected',await reducedPage.evaluate(()=>!PMP_ROOM.diagnostics.motion&&!document.querySelector('#motion').checked));await reducedPage.close();
const fallbackPage=await browser.newPage({viewport:{width:390,height:844}});await fallbackPage.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(name,...args){if(name.startsWith('webgl'))return null;return original.call(this,name,...args);};});await fallbackPage.goto('http://127.0.0.1:4173/player-three.html');await fallbackPage.waitForSelector('#fallback:not([hidden])');await fallbackPage.locator('#audio-files').setInputFiles(tone('Fallback audio.wav'));await fallbackPage.waitForFunction(()=>!PMP_PLAYER.state.paused);check('Audio and controls work without WebGL',true);await fallbackPage.screenshot({path:path.join(out,'three-player-fallback.png'),fullPage:true});await fallbackPage.close();
}catch(e){errors.push(e.stack);await page.screenshot({path:path.join(out,'three-player-test-failure.png'),fullPage:true});process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'three-player-checks.json'),JSON.stringify({date:new Date().toISOString(),checks:results,errors,pass:errors.length===0&&results.every(r=>r.pass),note:'Test WAV data generated in memory only for actual audio QA; no demo music shipped.'},null,2));console.log(JSON.stringify({checks:results.length,errors,pass:errors.length===0}));await browser.close();}})();
