import {getScene} from './player-three-collection.js';
const worlds={tidal:{category:'01 / THE LIVING OCEAN',line:'Somewhere between sound and infinity.'},monolith:{category:'02 / IMPOSSIBLE ARCHITECTURE',line:'Let your sound move mountains.'},aether:{category:'03 / THE COSMIC CURRENT',line:'Lose your edges. Find your universe.'}};
export function createLabShell({getCurrent,chooseScene,openWorld,getRoom,toast}){
 let current=null;const nav=document.querySelector('.lab-worlds');
 nav.onclick=e=>{const button=e.target.closest('[data-lab-scene]');if(button)chooseScene(button.dataset.labScene);};
 document.querySelector('#lab-tune').onclick=openWorld;
 const capture=document.createElement('button');capture.type='button';capture.className='text-btn lab-capture';capture.textContent='Save frame ↗';capture.setAttribute('aria-label','Save this world as an image');document.querySelector('.stage-bottom').prepend(capture);
 const preview=document.createElement('dialog');preview.className='lab-capture-preview';preview.setAttribute('aria-label','Your captured world');preview.innerHTML='<form method="dialog"><span>ONE MOMENT. ENTIRELY YOURS.</span><button aria-label="Close captured image">×</button></form><img alt="Your captured three-dimensional world"><div><p>This moment is yours to keep.</p><a download>Save PNG ↗</a></div>';document.body.append(preview);let capturedURL=null;
 preview.addEventListener('close',()=>{if(capturedURL)URL.revokeObjectURL(capturedURL);capturedURL=null;preview.querySelector('img').removeAttribute('src');capture.focus();});
 capture.onclick=async()=>{capture.disabled=true;try{const blob=await getRoom().captureFrame();if(capturedURL)URL.revokeObjectURL(capturedURL);capturedURL=URL.createObjectURL(blob);preview.querySelector('img').src=capturedURL;const link=preview.querySelector('a');link.href=capturedURL;link.download='beyond-'+getCurrent()+'.png';preview.querySelector('p').textContent='This moment is yours to keep.';preview.showModal();try{const response=await fetch('/api/captures?world='+encodeURIComponent(getCurrent()),{method:'POST',headers:{'Content-Type':'image/png'},body:blob});if(!response.ok)throw Error();const saved=await response.json();link.href=saved.url;link.download=saved.name;preview.querySelector('p').textContent=saved.width+' × '+saved.height+' · Saved in your project’s captures folder.';}catch{preview.querySelector('p').textContent='Image ready. Use Save PNG to keep a copy.';}}catch(error){toast(error.message||'Keep this world visible and try again.');}finally{capture.disabled=false;}};
 function tick(){const id=getCurrent();if(id===current)return;current=id;const scene=getScene(id),meta=worlds[id];document.body.dataset.labScene=id;document.querySelector('#room-heading').replaceChildren(document.createTextNode(scene.name),Object.assign(document.createElement('span'),{textContent:'.'}));document.querySelector('#lab-world-category').textContent=meta?.category||'FROM THE ORIGINAL COLLECTION';document.querySelector('#lab-world-line').textContent=meta?.line||scene.line;for(const button of nav.querySelectorAll('[data-lab-scene]'))button.setAttribute('aria-pressed',String(button.dataset.labScene===id));document.querySelector('#lab-tune').textContent=meta?'Shape this world ↗':'Explore the visual studio ↗';}
 tick();return{tick};
}
