const {chromium}=require('../../docs/design/2026-09-09-html-mockups/tools/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve(__dirname,'../verification'),checks=[],errors=[];
function ok(name,details){checks.push({name,passed:true,details});console.log('PASS '+name);}
function wave(){const seconds=7,rate=22050,count=rate*seconds,b=Buffer.alloc(44+count*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)b.writeInt16LE(Math.round(Math.sin(i/rate*440*Math.PI*2)*1500*Math.sin(i/count*Math.PI)),44+i*2);return b;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1504,height:1048},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});try{
await page.goto('http://127.0.0.1:4173/');await page.waitForFunction(()=>!!window.PMP?.initPage);await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('#prompt').inputValue(),'A peaceful night drive.\nWarm ’80s synths. No vocals.');ok('Composer and all application modules initialized');
await page.getByRole('button',{name:'All controls',exact:true}).click();assert.equal(await page.locator('.control-card').count(),100);await page.locator('#control-search').fill('lyrics');assert.ok(await page.locator('.control-card:visible').count()>4);await page.screenshot({path:path.join(output,'controls-desktop.png')});await page.locator('#control-search').fill('');await page.locator('[data-parameter="tempo_bpm"] summary').click();await page.locator('[data-enable="tempo_bpm"]').check();await page.locator('[data-path="tempo_bpm"]').fill('128');await page.locator('#apply-controls').click();assert.equal(await page.evaluate(()=>PMP.state.draft.tempo_bpm),128);ok('100 controls rendered, searched, edited and applied');
await page.locator('[data-action="select"][data-key="genres"]').click();await page.locator('[data-option-search="genres"]').fill('jazz');assert.ok(await page.locator('.choice').count()>0);await page.locator('.choice').first().click();await page.locator('#apply-quick').click();assert.match(await page.locator('#prompt').inputValue(),/Style:/);ok('Genre vocabulary search, selection and editable prompt integration');
await page.locator('[data-action="enhance"]').click();assert.ok((await page.locator('#enhanced-prompt').inputValue()).length>0);await page.locator('#use-enhanced').click();ok('Enhancement review and apply');
await page.locator('#create-button').click();assert.match(await page.locator('#modal-content').innerText(),/isn’t available in this local preview/);await page.locator('[data-action="close"]').first().click();ok('Unavailable creation is honest and preserves music brief');
await page.locator('.rail [href="explore.html"]').click();assert.equal(await page.locator('body').getAttribute('data-page'),'explore');await page.getByRole('tab',{name:'Moods',exact:true}).click();await page.getByRole('button',{name:'Focus',exact:true}).click();assert.equal(await page.locator('#results-title').innerText(),'Songs for Focus');await page.locator('[data-action="clear-category"]').click();await page.getByRole('tab',{name:'Genres',exact:true}).click();ok('Explore tabs and category results');
for(const id of ['hours','violet','coast','lights','ferry'])await page.locator(`[data-action="save"][data-id="${id}"]`).click();await page.locator('.search-launch').click();await page.locator('#global-search').fill('Night Drive');await page.locator('#search-results [data-action="track"]').first().click();await page.locator('#modal [data-action="save"]').click();await page.locator('#modal [data-action="close"]').click();await page.locator('.rail [href="library.html"]').click();await page.waitForURL('**/library.html');assert.equal(await page.locator('#library-content .song-card').count(),6);await page.screenshot({path:path.join(output,'library-populated-desktop.png'),fullPage:true});ok('Saving six real UI selections populates Library');
await page.locator('[data-action="new-playlist"]').click();await page.locator('#playlist-form input').fill('Night notes');await page.locator('#playlist-form [type="submit"]').click();assert.equal(await page.locator('.playlist-card').count(),1);await page.getByRole('tab',{name:'Saved songs',exact:true}).click();await page.locator('[data-action="song-menu"][data-id="hours"]').click();await page.locator('[data-action="playlist-add"]').click();await page.locator('[data-add-playlist]').click();assert.equal(await page.evaluate(()=>PMP.state.playlists[0].songs.length),1);await page.getByRole('tab',{name:'Playlists',exact:true}).click();await page.locator('.playlist-cover').click();assert.equal(await page.locator('#modal .track-row').count(),1);await page.locator('[data-action="playlist-rename"]').click();await page.locator('#playlist-form input').fill('After midnight');await page.locator('#playlist-form [type="submit"]').click();assert.match(await page.locator('.playlist-card').innerText(),/After midnight/);ok('Playlist creation, adding a song, opening and renaming');
await page.getByRole('tab',{name:'Saved songs',exact:true}).click();await page.locator('#library-search').fill('zzz-no-match');assert.match(await page.locator('#library-content').innerText(),/No saved songs match/);await page.locator('[data-action="clear-library-search"]').click();await page.locator('[data-action="save"][data-id="hours"]').click();assert.equal(await page.locator('#library-content .song-card').count(),5);await page.locator('#toast button').click();assert.equal(await page.locator('#library-content .song-card').count(),6);ok('Library search, remove and undo');
await page.locator('.rail [href="radio.html"]').click();await page.locator('[data-action="radio-filter"][data-key="mood"]').click();await page.locator('[data-simple-value="Sleep"]').click();assert.equal(await page.locator('#station-results .station-card').count(),1);ok('Radio filtering');
await page.locator('.account-link').click();await page.locator('#auth-form [name="email"]').fill('test@example.com');await page.locator('#password').fill('NotARealPassword');await page.locator('[data-action="password"]').click();assert.equal(await page.locator('#password').getAttribute('type'),'text');await page.locator('#auth-form [type="submit"]').click();assert.match(await page.locator('#auth-status').innerText(),/Sign-in isn’t available/);await page.locator('[data-action="reset-password"]').click();await page.locator('#secondary-auth [name="email"]').fill('test@example.com');await page.locator('#secondary-auth [type="submit"]').click();assert.match(await page.locator('#secondary-auth-status').innerText(),/isn’t available/);await page.locator('#modal [data-action="close"]').click();ok('Login visibility toggle, validation and truthful recovery state');
await page.locator('.auth-back').click();await page.locator('#audio-files').setInputFiles([{name:'QA audio.wav',mimeType:'audio/wav',buffer:wave()}]);await page.waitForFunction(()=>PMP.state.current?.title==='QA audio'&&!document.querySelector('#audio').paused);await page.waitForTimeout(450);const before=await page.locator('#audio').evaluate(a=>a.currentTime);await page.locator('.rail [href="explore.html"]').click();const after=await page.locator('#audio').evaluate(a=>a.currentTime);assert.ok(after>=before);assert.equal(await page.locator('#audio').evaluate(a=>a.paused),false);assert.equal(await page.locator('audio').count(),1);ok('Real HTMLAudioElement playback survives route navigation',{before,after});
await page.locator('[data-action="play"]').click();assert.equal(await page.locator('#audio').evaluate(a=>a.paused),true);await page.locator('#seek').fill('500');await page.locator('#seek').dispatchEvent('input');assert.ok(Math.abs(await page.locator('#audio').evaluate(a=>a.currentTime)-3.5)<.3);await page.locator('#volume').fill('0.3');await page.locator('#volume').dispatchEvent('input');assert.equal(await page.locator('#audio').evaluate(a=>a.volume),.3);ok('Real pause, seeking and volume');
await page.locator('[data-action="expand"]').last().click();await page.screenshot({path:path.join(output,'expanded-player-desktop.png')});await page.locator('#expanded-continuation').click();assert.equal(await page.locator('#expanded-continuation').isChecked(),false);await page.locator('#modal [data-action="close"]').click();ok('Expanded player and unavailable continuation state');
await page.reload();await page.waitForFunction(()=>PMP.state.songs.some(s=>s.local&&s.title==='QA audio'));assert.equal(await page.evaluate(()=>PMP.state.playlists[0].name),'After midnight');ok('Favorites, playlists and imported audio survive reload in IndexedDB');
for(const [name,width,height]of [['desktop',1504,1048],['tablet',820,1180],['mobile',390,844]]){await page.setViewportSize({width,height});for(const route of ['index','login','explore','radio','library']){await page.goto('http://127.0.0.1:4173/'+route+'.html');await page.waitForFunction(()=>!!window.PMP?.initPage);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(output,`${route}-${name}.png`),fullPage:true});const overflow=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(overflow.scroll<=width+1,`${route} ${name} overflows: ${JSON.stringify(overflow)}`);}ok(`All five ${name} routes render without horizontal overflow`);}
assert.deepEqual(errors,[]);ok('No browser JavaScript errors or failed HTTP requests');
}catch(e){errors.push(e.stack);console.error(e.stack);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});process.exitCode=1;}finally{fs.writeFileSync(path.join(output,'browser-checks.json'),JSON.stringify({checks,errors,note:'QA audio is a short generated test tone supplied only to the isolated browser, not shipped as music.'},null,2));await browser.close();}})();
