(() => {
'use strict';
const P=window.PMP,{$,$$,state,cfg,song,station,art,icon,esc,dialog,closeDialog,toast,storage}=P,audio=$('#audio'),canvas=$('#waveform'),ctx=canvas.getContext('2d');let peaks=null,decodeId=0,importTarget=null,dbPromise;
const time=n=>!Number.isFinite(n)?'0:00':`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function draw(){const w=canvas.width,h=canvas.height,p=Number.isFinite(audio.duration)?audio.currentTime/audio.duration:0;ctx.clearRect(0,0,w,h);if(!peaks){ctx.fillStyle='#454c62';ctx.fillRect(0,h/2-1,w,2);ctx.fillStyle='#b768fa';ctx.fillRect(0,h/2-1,w*p,2);return;}const bw=w/peaks.length;peaks.forEach((v,i)=>{const bh=Math.max(2,v*(h-4));ctx.fillStyle=i/peaks.length<p?'#b65bff':'#4b4567';ctx.fillRect(i*bw,h/2-bh/2,Math.max(1,bw-1),bh);});}
async function decode(s){const token=++decodeId;peaks=null;draw();try{const data=s.blob?await s.blob.arrayBuffer():await(await fetch(s.url)).arrayBuffer();if(data.byteLength>80*1024*1024)return;const ac=new(window.AudioContext||window.webkitAudioContext)();let buffer;try{buffer=await ac.decodeAudioData(data);}finally{await ac.close();}if(token!==decodeId)return;const samples=buffer.getChannelData(0),block=Math.ceil(samples.length/220),values=[];for(let i=0;i<220;i++){let max=0;for(let j=i*block;j<Math.min(samples.length,(i+1)*block);j+=Math.max(1,Math.floor(block/150)))max=Math.max(max,Math.abs(samples[j]));values.push(max);}const max=Math.max(...values,.001);peaks=values.map(v=>v/max);draw();}catch{/* CORS-protected audio can play without a decoded waveform. */}}
function update(){const s=state.current;document.body.classList.toggle('has-audio',!!s);$('#track-title').textContent=s?.title||'Your next sound';$('#track-origin').textContent=s?(state.station?`From ${station(state.station)?.name||'your station'}`:s.origin||'From the library'):'Choose a song to begin';if(s&&$('.player-art').dataset.track!==s.id){$('.player-art').innerHTML=art(s.art);$('.player-art').dataset.track=s.id;}for(const b of $$('[data-action="play"]')){b.innerHTML=icon(audio.paused?'play':'pause');b.setAttribute('aria-label',audio.paused?'Play':'Pause');}$('#seek').disabled=!Number.isFinite(audio.duration);$('#duration').textContent=time(audio.duration);$('#elapsed').textContent=time(audio.currentTime);$('#seek').value=Number.isFinite(audio.duration)?audio.currentTime/audio.duration*1000:0;$('#queue-status').textContent=state.autofilling?'Creating what’s next…':state.queue.length?'Next song ready':'Nothing queued yet';$('#continuation').checked=state.continuation;for(const b of $$('.portal-play')){const active=b.dataset.id===state.station&&!audio.paused;b.innerHTML=icon(active?'pause':'play');b.setAttribute('aria-label',`${active?'Pause':'Play'} ${station(b.dataset.id)?.name||'station'}`);}P.syncSaved();draw();if($('#expanded-time')){$('#expanded-time').textContent=time(audio.currentTime);$('#expanded-duration').textContent=time(audio.duration);$('#expanded-seek').disabled=!Number.isFinite(audio.duration);$('#expanded-seek').value=$('#seek').value;$('#expanded-continuation').checked=state.continuation;}}
function unavailable(s){dialog(s.title,`<div class="unavailable-art">${art(s.art)}</div><p class="notice">Audio isn’t available for this song yet. Save it to your collection or add an audio file to listen.</p><div class="inline-actions"><button class="primary" data-action="attach-audio" data-id="${esc(s.id)}">${icon('upload')}Add audio to this song</button><button class="secondary" data-action="save" data-id="${esc(s.id)}">${icon('heart')}Save song</button></div>`);}
async function playTrack(id,{keepStation=false,force=false,history=true}={}){const s=song(id);if(!s)return;closeDialog();if(!s.url){unavailable(s);return;}if(!keepStation)state.station=null;if(state.current?.id===id&&!force){try{if(audio.paused)await audio.play();else audio.pause();}catch{toast('Press play to start your song.');}update();return;}if(state.current&&history)state.history.unshift(state.current.id);state.current=s;audio.src=s.url;audio.load();update();decode(s);try{await audio.play();}catch(err){toast(err.name==='NotAllowedError'?'Your song is ready. Press play to listen.':'This audio file couldn’t be played. Choose another.');}if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:s.title,artist:'PlayMusicPrompts',album:state.station?station(state.station)?.name:'Your music'});update();maybeContinue();}
async function next(){if(state.queue.length){await playTrack(state.queue.shift(),{keepStation:true,force:true});}else if(state.autofilling)toast('The next song is still being created.');else{toast('Nothing queued yet');openQueue();}maybeContinue();}
async function previous(){if(audio.currentTime>3){audio.currentTime=0;return;}const id=state.history.shift();if(id){if(state.current)state.queue.unshift(state.current.id);await playTrack(id,{keepStation:true,force:true,history:false});}else audio.currentTime=0;}
function queueTrack(id){const s=song(id);if(!s)return;if(!s.url){unavailable(s);return;}state.queue.unshift(id);update();toast(`${s.title} is up next`);}
const playable=()=>state.songs.filter(s=>s.url);
function random(){const pool=playable();if(!pool.length){dialog('Start with a sound.',`<div class="empty-state">${icon('music')}<h3>Your listening starts here.</h3><p>Add an audio file to hear it in the player. Your files stay on this device.</p><button class="primary" data-action="import">${icon('upload')}Add audio files</button></div>`);return;}playTrack(pool[Math.floor(Math.random()*pool.length)].id,{force:true});}
function row(s,action='play'){return `<div class="track-row"><button class="row-art" data-action="track" data-id="${esc(s.id)}" aria-label="Play ${esc(s.title)}">${art(s.art)}</button><div><strong>${esc(s.title)}</strong><small>${esc(s.origin||'From the library')}</small></div><button class="icon-button" data-action="${action==='queue'?'queue-remove':'track'}" data-id="${esc(s.id)}" aria-label="${action==='queue'?'Remove from queue':'Play'} ${esc(s.title)}">${icon(action==='queue'?'close':'play')}</button></div>`;}
function openQueue(){dialog('Up next',`${state.current?`<p class="section-label">${audio.paused?'Current song':'Now playing'}</p>${row(state.current)}`:''}<div class="queue-heading"><p class="section-label">Up next</p><button class="text-button" data-action="import">${icon('plus')}Add music</button></div>${state.queue.length?state.queue.map(song).filter(Boolean).map(s=>row(s,'queue')).join(''):'<div class="queue-empty">Nothing queued yet</div>'}${state.history.length?`<p class="section-label">Recently played</p>${state.history.slice(0,4).map(song).filter(Boolean).map(s=>row(s)).join('')}`:''}`,`<button class="secondary" data-action="random">Play from the library</button>`);}
function expand(){dialog(state.current?.title||'Your next sound',`<div class="expanded-art">${art(state.current?.art||'night')}</div><p class="expanded-origin">${esc(state.current?.origin||'Choose a song to begin')}</p><div class="expanded-progress"><span id="expanded-time">0:00</span><input type="range" id="expanded-seek" aria-label="Seek in expanded player" min="0" max="1000" value="0"><span id="expanded-duration">0:00</span></div><div class="expanded-transport"><button class="icon-button" data-action="previous" aria-label="Previous song">${icon('previous')}</button><button class="play-button" data-action="play" aria-label="Play">${icon('play')}</button><button class="icon-button" data-action="next" aria-label="Next song">${icon('next')}</button></div><div class="expanded-options"><button class="text-button" data-action="save-current">${icon('heart')}Save song</button><button class="text-button" data-action="queue">${icon('queue')}Up next</button></div><label class="expanded-volume">${icon('volume')}<input type="range" id="expanded-volume" min="0" max="1" step="0.01" value="${audio.volume}" aria-label="Volume in expanded player"></label><label class="switch expanded-switch"><input type="checkbox" id="expanded-continuation" ${state.continuation?'checked':''}><span></span>Keep it going</label><p class="expanded-help">What you play and skip helps shape the next song.</p>`);$('#modal').classList.add('player-dialog');update();}
async function continuation(on){if(on&&!cfg.adapters.continue){update();toast('Continuous creation isn’t available in this preview. You can still queue songs.');return;}state.continuation=on;update();toast(on?'On. New songs will follow this one.':'Off. New songs won’t be added automatically.');if(on)maybeContinue();}
async function maybeContinue(){if(!state.continuation||!state.current||state.autofilling||state.queue.length||!cfg.adapters.continue)return;state.autofilling=true;update();try{const result=await cfg.adapters.continue({current:publicTrack(state.current),history:state.history.slice(0,20),preferences:state.draft});if(state.continuation){const s=register(result);state.queue.push(s.id);}}catch{if(state.continuation)toast('We couldn’t create the next song. Try again or play from the library.');}finally{state.autofilling=false;update();}}
function publicTrack(s){const{blob,...track}=s;return track;}
function register(r){if(!r||!r.url||!r.title)throw Error('No playable song was returned.');const s={id:r.id||crypto.randomUUID(),art:'night',origin:'Made for you',created:true,...r,illustrative:false},i=state.songs.findIndex(x=>x.id===s.id);if(i>=0)state.songs[i]=s;else state.songs.push(s);storage.set('creations',state.songs.filter(x=>x.created&&!x.local).map(publicTrack));return s;}
function stationPool(id){const st=station(id);return playable().filter(s=>s.stationId===id||s.stationIds?.includes(id)||(!s.stationId&&s.genre===st.genre));}
async function startStation(id){const st=station(id);if(!st)return;if(state.station===id&&state.current){audio.paused?audio.play().catch(()=>toast('Press play to continue.')):audio.pause();return;}const pool=stationPool(id);if(!pool.length){dialog(st.name,`<div class="unavailable-art">${art(st.art)}</div><p class="notice">${esc(st.description)}<br>There are no playable songs in this station yet.</p><div class="inline-actions"><button class="primary" data-action="import">${icon('upload')}Add audio files</button><a href="index.html" data-route class="secondary">Create a song</a></div>`);return;}state.station=id;state.queue=pool.slice(1).map(s=>s.id);await playTrack(pool[0].id,{keepStation:true,force:true});}
function playCollection(ids){const pool=ids.map(song).filter(s=>s?.url);if(!pool.length){toast('Add audio to your saved songs to play this collection.');return;}state.queue=pool.slice(1).map(s=>s.id);playTrack(pool[0].id,{force:true});}
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('pmp-local-audio',1);r.onupgradeneeded=()=>r.result.createObjectStore('tracks',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return dbPromise;}
async function saveLocal(s){const store=await db();await new Promise((resolve,reject)=>{const tx=store.transaction('tracks','readwrite'),{url,...record}=s;tx.objectStore('tracks').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function restore(){for(const s of storage.get('creations',[]))if(s.id&&s.url&&!song(s.id))state.songs.push(s);try{const store=await db(),records=await new Promise((resolve,reject)=>{const r=store.transaction('tracks').objectStore('tracks').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});for(const r of records){if(!r.blob)continue;const s={...r,url:URL.createObjectURL(r.blob)},i=state.songs.findIndex(x=>x.id===s.id);if(i>=0)state.songs[i]=s;else state.songs.push(s);}}catch{}P.renderLibrary();}
async function importFiles(files){const target=importTarget;importTarget=null;const added=[];for(const [i,file] of [...files].entries()){if(!file.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|flac|aac|opus)$/i.test(file.name))continue;const existing=i===0&&target?song(target):null,s={...(existing||{}),id:existing?.id||crypto.randomUUID(),title:existing?.title||file.name.replace(/\.[^.]+$/,''),art:existing?.art||'night',origin:'From your device',local:true,illustrative:false,blob:file,url:URL.createObjectURL(file)},old=state.songs.findIndex(x=>x.id===s.id);if(old>=0)state.songs[old]=s;else state.songs.push(s);if(!state.saved.some(r=>r.id===s.id))state.saved.unshift({id:s.id,savedAt:Date.now()});try{await saveLocal(s);}catch{toast('Audio is ready for this visit. Your browser couldn’t store the file.');}added.push(s);}P.persist();P.renderLibrary();P.syncSaved();if(added.length){state.queue.push(...added.slice(1).map(s=>s.id));await playTrack(added[0].id,{force:true});toast(`${added.length===1?'Your audio is':`${added.length} audio files are`} ready`);}else toast('Choose an audio file to continue.');$('#audio-files').value='';}
Object.assign(P,{audio,updatePlayer:update,playTrack,queueTrack,random,row,registerTrack:register,playCollection,restoreAudio:restore});
Object.assign(P.actions,{track:b=>playTrack(b.dataset.id),play:()=>{if(!state.current)random();else if(audio.paused)audio.play().catch(()=>toast('This song is unavailable. Choose another.'));else audio.pause();},previous,next,random,queue:openQueue,expand,station:b=>startStation(b.dataset.id),'play-next':b=>queueTrack(b.dataset.id),'queue-remove':b=>{const i=state.queue.indexOf(b.dataset.id);if(i>=0)state.queue.splice(i,1);update();openQueue();},shuffle:b=>{state.shuffle=!state.shuffle;b.setAttribute('aria-pressed',String(state.shuffle));if(state.shuffle)for(let i=state.queue.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.queue[i],state.queue[j]]=[state.queue[j],state.queue[i]];}toast(state.shuffle?'Shuffle on':'Shuffle off');},repeat:b=>{state.repeat=!state.repeat;b.setAttribute('aria-pressed',String(state.repeat));toast(state.repeat?'Repeat song on':'Repeat off');},mute:b=>{audio.muted=!audio.muted;b.innerHTML=icon(audio.muted?'mute':'volume');b.setAttribute('aria-label',audio.muted?'Unmute':'Mute');},import:()=>{importTarget=null;$('#audio-files').click();},'attach-audio':b=>{importTarget=b.dataset.id;$('#audio-files').click();}});
P.onInput.push(el=>{if(['volume','expanded-volume'].includes(el.id)){audio.volume=Number(el.value);audio.muted=false;$('#volume').value=el.value;storage.set('volume',audio.volume);}if(['seek','expanded-seek'].includes(el.id)&&Number.isFinite(audio.duration))audio.currentTime=audio.duration*Number(el.value)/1000;});P.onChange.push(el=>{if(el.id==='audio-files')importFiles(el.files);if(['continuation','expanded-continuation'].includes(el.id))continuation(el.checked);});
for(const ev of ['play','pause','loadedmetadata','durationchange','timeupdate','playing'])audio.addEventListener(ev,update);
audio.addEventListener('waiting',()=>{if(state.current)$('#track-origin').textContent='Loading audio…';});audio.addEventListener('error',()=>{if(state.current)toast('This song is unavailable. Choose another audio file.');update();});audio.addEventListener('ended',()=>{if(state.repeat){audio.currentTime=0;audio.play().catch(()=>{});}else if(state.queue.length)next();else if(state.station){state.queue=stationPool(state.station).filter(s=>s.id!==state.current.id).map(s=>s.id);if(state.queue.length)next();else{audio.currentTime=0;audio.play().catch(()=>{});}}else if(state.continuation)maybeContinue();update();});
window.addEventListener('offline',()=>toast('You’re offline. Audio saved on this device is still available.'));
if('mediaSession'in navigator)for(const [name,fn]of Object.entries({play:()=>audio.play(),pause:()=>audio.pause(),previoustrack:previous,nexttrack:next,seekto:d=>{audio.currentTime=d.seekTime;}})){try{navigator.mediaSession.setActionHandler(name,fn);}catch{}}
audio.volume=Math.max(0,Math.min(1,storage.get('volume',.7)));$('#volume').value=audio.volume;draw();
})();
