import {createPerformanceDirector} from './player-three-performance.js';
import {createVisualStore} from './player-three-visual-settings.js';
import {createVisualStudio} from './player-three-visual-studio.js';
import {createSessionControls} from './player-three-session.js';
import {getScene,createSceneSelection} from './player-three-collection.js';
import {createRoomStore} from './player-three-store.js';
import {motionPreference,motionEnabled} from './player-three-motion.js';
import {WORLDS,getWorld,worldStyle,colorRGB} from './player-three-worlds.js';
import {createSoundControls} from './player-three-sound-ui.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const icons={clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18ZM12 7v5l3 2',play:'M8 5l11 7-11 7Z',pause:'M8 5v14M16 5v14',previous:'M6 5v14M18 5l-10 7 10 7Z',next:'M18 5v14M6 5l10 7-10 7Z',shuffle:'M4 7h2c5 0 6 10 11 10h3m-3-3 3 3-3 3M4 17h2c1.4 0 2.5-.9 3.5-2.1M14 8c1-1 2-1 3-1h3m-3-3 3 3-3 3',repeat:'M4 10V7h15m-3-3 3 3-3 3M20 14v3H5m3-3-3 3 3 3',volume:'M4 9h4l5-4v14l-5-4H4ZM16 9a5 5 0 0 1 0 6m3-9a9 9 0 0 1 0 12',mute:'M4 9h4l5-4v14l-5-4H4ZM17 9l5 6m0-6-5 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',heart:'M20.8 5.9a5.5 5.5 0 0 0-7.8 0l-1 1-1-1a5.5 5.5 0 0 0-7.8 7.8L12 22l8.8-8.3a5.5 5.5 0 0 0 0-7.8Z',expand:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',focus:'M8 4H4v4m12-4h4v4M4 16v4h4m12-4v4h-4M9 9h6v6H9Z',queue:'M4 6h16M4 12h10M4 18h8m5-4 5 4-5 4Z',sliders:'M5 3v4m0 4v10M12 3v10m0 4v4M19 3v2m0 4v12M2 7h6m1 10h6m1-12h6',sparkles:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',keyboard:'M3 5h18v14H3ZM6 8h.1M10 8h.1M14 8h.1M18 8h.1M6 11h.1M10 11h.1M14 11h.1M18 11h.1M7 15h10',music:'M9 18V5l11-2v13M9 8l11-2M9 18a3 3 0 1 1-3-3c1.7 0 3 1.3 3 3Zm11-2a3 3 0 1 1-3-3c1.7 0 3 1.3 3 3Z',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5ZM12 14v3',orbit:'M20 10a8 8 0 1 0-2 8m2-14v6h-6',move:'M12 2v20M2 12h20M9 5l3-3 3 3M9 19l3 3 3-3M5 9l-3 3 3 3m14-6 3 3-3 3',up:'m6 15 6-6 6 6',down:'m6 9 6 6 6-6'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.music}"/></svg>`;
$$('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d;}catch{return d;}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}}};
const roomStore=createRoomStore(storage,crypto.randomUUID());
const prefs={...roomStore.readPreferences(),...roomStore.readSession()},reduced=matchMedia('(prefers-reduced-motion: reduce)');
const visualStore=createVisualStore(storage);let visualStudio=null,performanceDirector=null;
let room=null;const visualState={model:getScene(prefs.model).id,world:getWorld(prefs.world).id,spin:prefs.spin!==false,rpm:Number.isFinite(prefs.rpm)?Math.max(0,Math.min(45,prefs.rpm)):8,autoOrbit:!!prefs.autoOrbit,reactivity:Number.isFinite(prefs.reactivity)?Math.max(0,Math.min(2,prefs.reactivity)):1,form:['halo','orbit','wave'].includes(prefs.form)?prefs.form:'halo',intensity:Number.isFinite(prefs.intensity)?prefs.intensity:.65,motionPreference:motionPreference(prefs),motion:motionEnabled(motionPreference(prefs),reduced.matches),quality:['auto','high','low'].includes(prefs.quality)?prefs.quality:'auto'};

let manualScene=visualState.model;
function fallback(message){$('#fallback').hidden=false;$('#fallback-message').textContent=message;$('#scene').style.visibility='hidden';}
import('./player-three-scene.js').then(({createListeningRoom})=>{try{room=createListeningRoom($('#scene'),fallback);window.PMP_ROOM=room;room.setWorld(visualState.world);room.setModel(visualState.model);room.setForm(visualState.form);room.setIntensity(visualState.intensity);room.setMotion(visualState.motion);room.setQuality(visualState.quality);room.setSpin(visualState.spin,visualState.rpm);room.setAutoOrbit(visualState.autoOrbit);room.setReactivity(visualState.reactivity);room.setVisualSettings(visualStudio?.settings||visualStore.read().settings);}catch{fallback('Your music is ready. The 3D scene is unavailable in this browser.');}}).catch(()=>fallback('The 3D scene couldn’t load. You can still enjoy your music.'));
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
const audio=$('#audio'),queue=[],available=[],objectURLs=new Set(),history=[],shufflePlayed=new Set();let current=null,ctx=null,source=null,analyser=null,gain=null,headroom=null,filters=[],bins=new Uint8Array(1024),eq=[0,0,0,0,0],volume=Number.isFinite(prefs.volume)?Math.max(0,Math.min(1,prefs.volume)):.7,muted=false,repeat=0,shuffle=false,selectToken=0,waveToken=0,peaks=null,loopA=null,loopB=null,dbPromise=null,currentPanel=null,returnFocus=null,restoring=false,saveTimer=null;
const fmt=seconds=>{if(!Number.isFinite(seconds)||seconds<0)return'0:00';const h=Math.floor(seconds/3600),m=Math.floor(seconds/60)%60,s=Math.floor(seconds%60);return(h?`${h}:`:'')+`${h?String(m).padStart(2,'0'):m}:${String(s).padStart(2,'0')}`;};
const trackWorld=track=>WORLDS.some(w=>w.id===track?.art)?track.art:['focus','rest'].includes(track?.art)?'deep':['coast','morning'].includes(track?.art)?'glow':'night';
function persist(scope='position'){
  if(restoring&&['session','advance','position'].includes(scope))return false;
  const session={order:queue.map(track=>track.id),current:current?.id??null,time:Number.isFinite(audio.currentTime)?audio.currentTime:0};
  if(scope==='session')return roomStore.claimSession(session);
  if(scope==='advance')return roomStore.updateSession(session);
  if(scope==='position')return roomStore.savePosition(session.current,session.time);
  return roomStore.savePreference(scope,scope==='volume'?volume:visualState[scope]);
}
function seekTo(time){if(!current||!Number.isFinite(audio.duration))return;audio.currentTime=Math.max(0,Math.min(audio.duration,time));persist('session');sync();}
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('pmp-local-audio',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('tracks'))request.result.createObjectStore('tracks',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Storage is busy'));});return dbPromise;}
async function saveTrack(track){const store=await db();await new Promise((resolve,reject)=>{const tx=store.transaction('tracks','readwrite');const{url,...record}=track;tx.objectStore('tracks').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
let sessionControls=null;const soundControls=createSoundControls({audio,storage,toast});
async function startAudio(){const started=await soundControls.start();ctx=started.context;analyser=started.rack.analysers[0];bins=started.rack.bins;soundControls.setVolume(volume,muted);if(sessionControls?.onAudioStart()===false)throw new Error('Your sleep timer has ended. Press play to keep listening.');}
function updateGain(){soundControls.setVolume(volume,muted);$('#volume').value=volume;$('#volume-label').value=Math.round(volume*100)+'%';$('#mute').innerHTML=icon(muted||!volume?'mute':'volume');$('#mute').setAttribute('aria-label',muted?'Unmute':'Mute');$('#sound-volume').value=volume;$('#sound-volume-label').value=Math.round(volume*100)+'%';$('#sound-mute').innerHTML=icon(muted||!volume?'mute':'volume');$('#sound-mute').setAttribute('aria-label',muted?'Unmute':'Mute');}
function syncFavorite(){const saved=storage.get('pmp.saved',[]),isSaved=!!current&&saved.some(x=>x.id===current.id);$('#favorite').disabled=!current;$('#favorite').setAttribute('aria-pressed',String(isSaved));$('#favorite').setAttribute('aria-label',isSaved?'Remove song from saved':'Save song');$('#favorite').style.color=isSaved?'var(--accent)':'';}
function renderQueue(){const focused=document.activeElement,focusId=focused?.closest('.queue-item')?.dataset.id,focusAction=focused?.dataset.action,hadQueueFocus=$('#queue-list').contains(focused);const fragment=document.createDocumentFragment();queue.forEach((track,i)=>{const query=$('#queue-search').value.trim().toLocaleLowerCase();if(query&&!String(track.title).toLocaleLowerCase().includes(query))return;const li=document.createElement('li');li.className='queue-item'+(track.id===current?.id?' current':'');li.dataset.id=track.id;li.innerHTML=`<button class="queue-play" data-action="select" aria-label="Play ${escape(track.title)}"><span class="scene-art ${trackWorld(track)}" style="${worldStyle(trackWorld(track))}"></span><span class="queue-copy"><strong>${escape(track.title)}</strong><small>${track.id===current?.id?(audio.paused?'Selected':'Now playing'):`${String(i+1).padStart(2,'0')} · ${track.local?'From your device':'From your library'}`}</small></span></button><div class="queue-actions"><button class="icon-btn" data-action="up" aria-label="Move ${escape(track.title)} earlier" ${i===0?'disabled':''}>${icon('up')}</button><button class="icon-btn" data-action="down" aria-label="Move ${escape(track.title)} later" ${i===queue.length-1?'disabled':''}>${icon('down')}</button></div><button class="icon-btn" data-action="remove" aria-label="Remove ${escape(track.title)} from queue">${icon('close')}</button>`;fragment.append(li);});$('#queue-list').replaceChildren(fragment);$('#queue-no-results').hidden=!queue.length||$('#queue-list').children.length>0;$('#queue-count').textContent=queue.length;$('#empty-queue').hidden=queue.length>0;$('#clear-queue').disabled=queue.length===0;$('#restore-library').hidden=!available.some(t=>!queue.some(q=>q.id===t.id));if(hadQueueFocus&&currentPanel?.id==='queue-panel'){const same=$$('.queue-item').find(el=>el.dataset.id===focusId)?.querySelector(`[data-action="${focusAction}"]`);(same&&!same.disabled?same:$('#queue-list button:not(:disabled)')||$('#queue-panel .close-panel')).focus();}}
function sync(){const playing=!audio.paused&&!audio.ended;$('#play').innerHTML=icon(playing?'pause':'play');$('#play').setAttribute('aria-label',playing?'Pause':'Play');$('#elapsed').textContent=fmt(audio.currentTime);$('#duration').textContent=fmt(audio.duration);$('#seek').disabled=!current||!Number.isFinite(audio.duration)||audio.duration<=0;$('#seek').value=Number.isFinite(audio.duration)&&audio.duration>0?Math.round(audio.currentTime/audio.duration*1000):0;$('#seek').setAttribute('aria-valuetext',`${fmt(audio.currentTime)} of ${fmt(audio.duration)}`);$('#stage-status').textContent=playing?(visualState.motion?'YOUR SOUND, ALIVE':'PLAYING · MOTION OFF'):current?'TAKE YOUR TIME':'READY FOR YOUR SOUND';$('#output-status').textContent=playing?(muted||volume===0?'Sound muted':'Listening, in full color'):'Made for deep listening';$('#track-title').textContent=current?.title||'Make this moment yours.';$('#track-title').title=current?.title||'';$('#track-origin').textContent=current?(current.local?'FROM YOUR DEVICE':'FROM YOUR LIBRARY'):'YOUR NEXT OBSESSION';$('#track-detail').textContent=current?(current.local?'Your music. Your world.':'In your listening room'):'Add a song to begin';$('#track-art').className='track-art '+(current?trackWorld(current):visualState.world);$('#track-art').style.cssText=worldStyle(current?trackWorld(current):visualState.world);syncFavorite();drawWave();}
async function loadWave(track,token){peaks=null;drawWave();if(!track.blob||track.blob.size>80*1024*1024||!ctx)return;try{const buffer=await track.blob.arrayBuffer();if(token!==waveToken)return;const decoded=await ctx.decodeAudioData(buffer);if(token!==waveToken)return;const channels=Array.from({length:decoded.numberOfChannels},(_,i)=>decoded.getChannelData(i)),channel=channels[0],out=new Float32Array(320),step=Math.max(1,Math.floor(channel.length/out.length));let largest=0;for(let i=0;i<out.length;i++){let sum=0,count=0;for(let k=i*step;k<Math.min(channel.length,(i+1)*step);k+=Math.max(1,Math.floor(step/160))){for(const ch of channels){sum+=ch[k]*ch[k];count++;}}out[i]=Math.sqrt(sum/Math.max(1,count));largest=Math.max(largest,out[i]);}for(let i=0;i<out.length;i++)out[i]/=largest||1;peaks=out;drawWave();}catch{if(token===waveToken){peaks=null;drawWave();}}}
async function select(track,{play=true,time=0,remember=true,claim=true}={}){if(!track)return;const token=++selectToken;++waveToken;const previousId=current?.id;if(remember&&previousId&&previousId!==track.id)history.push(previousId);current=track;if(shuffle)shufflePlayed.add(track.id);audio.pause();audio.src=track.url;audio.load();peaks=null;loopA=loopB=null;syncLoop();sync();renderQueue();persist(claim?'session':'advance');if('mediaSession'in navigator&&'MediaMetadata'in window)navigator.mediaSession.metadata=new MediaMetadata({title:track.title,artist:track.local?'From your device':'PlayMusicPrompts',album:'The Listening Room'});if(time>0)audio.addEventListener('loadedmetadata',()=>{if(token===selectToken&&Number.isFinite(audio.duration))audio.currentTime=Math.min(time,Math.max(0,audio.duration-1));},{once:true});if(play){try{await startAudio();if(token!==selectToken)return;await audio.play();loadWave(track,waveToken);}catch(error){if(token===selectToken&&error.name!=='AbortError')toast(audio.error?'This file couldn’t play. Try another audio file.':error.message||'Press play to start listening.');}}else if(ctx)loadWave(track,waveToken);}
async function togglePlay(options={}){const claim=options?.claim!==false;if(!current){if(queue.length)await select(queue[0]);else $('#audio-files').click();return;}if(!audio.paused){audio.pause();return;}try{await startAudio();if(claim)persist('session');await audio.play();if(!peaks)loadWave(current,++waveToken);}catch(error){toast(error.message==='Your sleep timer has ended. Press play to keep listening.'?error.message:'This audio couldn’t start. Try another file.');}}
function goNext(automatic=false){if(!queue.length)return;const index=queue.findIndex(t=>t.id===current?.id);let target;if(shuffle){let pool=queue.filter(t=>!shufflePlayed.has(t.id));if(!pool.length){if(automatic&&repeat!==1){audio.pause();sync();return;}shufflePlayed.clear();pool=queue.filter(t=>queue.length===1||t.id!==current?.id);}target=pool[Math.floor(Math.random()*pool.length)];}else if(index+1<queue.length)target=queue[index+1];else if(repeat===1||!automatic)target=queue[0];if(target)select(target,{claim:!automatic});else{audio.pause();sync();}}
function previous(){if(audio.currentTime>3){seekTo(0);return;}let target;while(history.length&&!target){const id=history.pop();target=queue.find(t=>t.id===id);}if(!target){const index=queue.findIndex(t=>t.id===current?.id);target=queue[(index-1+queue.length)%queue.length];}if(target)select(target,{remember:false});}
function clearCurrent(){shufflePlayed.clear();history.splice(0);++selectToken;++waveToken;audio.pause();audio.removeAttribute('src');audio.load();current=null;peaks=null;loopA=loopB=null;syncLoop();sync();renderQueue();persist('session');if('mediaSession'in navigator)navigator.mediaSession.metadata=null;}
async function importFiles(fileList){let contextStart=startAudio().catch(()=>{});await ready;await contextStart;const files=[...fileList],added=[];let skipped=0,storageFailure=false;for(const file of files){if((!file.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|flac|aac|opus)$/i.test(file.name))||!file.size){skipped++;continue;}if(file.size>256*1024*1024){skipped++;continue;}const track={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),art:visualState.world,origin:'From your device',local:true,illustrative:false,blob:file,url:URL.createObjectURL(file)};objectURLs.add(track.url);queue.push(track);available.push(track);added.push(track);try{await saveTrack(track);}catch{storageFailure=true;}}if(added.length){renderQueue();persist('session');await select(added[0]);toast(storageFailure?'Music added for this visit. Browser storage is unavailable.':`${added.length===1?'Your song is':`${added.length} songs are`} ready.${skipped?' Some files were unsupported, empty, or over 256 MB.':''}`);}else toast('Choose a supported audio file under 256 MB.');$('#audio-files').value='';}
async function restore(){restoring=true;const sources=[];try{const connection=await db();const records=await new Promise((resolve,reject)=>{const req=connection.transaction('tracks').objectStore('tracks').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});for(const track of records){if(!track.blob)continue;const url=URL.createObjectURL(track.blob);objectURLs.add(url);sources.push({...track,url});}}catch{toast('Device storage is unavailable. You can still add music for this visit.');}for(const track of [...(window.PMP_CONFIG?.catalog||[]),...storage.get('pmp.creations',[])]){if(!track.id||!track.url||sources.some(t=>t.id===track.id))continue;try{const url=new URL(track.url,location.href);if(['https:','http:'].includes(url.protocol))sources.push({...track,url:url.href,local:false});}catch{}}
  available.push(...sources);const order=Array.isArray(prefs.order)?prefs.order:null;if(order){for(const id of order){const track=sources.find(t=>t.id===id);if(track)queue.push(track);}}else queue.push(...sources);renderQueue();const selected=queue.find(t=>t.id===prefs.current)||queue[0];if(selected)await select(selected,{play:false,time:Number(prefs.time)||0});restoring=false;sync();return true;
}
const ready=restore();sessionControls=createSessionControls({audio,storage,sound:soundControls,toast,getTrack:()=>current,format:fmt,redraw:drawWave,seek:seekTo});
function drawWave(){const canvas=$('#waveform'),rect=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);if(!rect.width)return;if(canvas.width!==Math.round(rect.width*ratio)||canvas.height!==Math.round(rect.height*ratio)){canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);}const g=canvas.getContext('2d');g.setTransform(ratio,0,0,ratio,0,0);const w=rect.width,h=rect.height;g.clearRect(0,0,w,h);const progress=Number.isFinite(audio.duration)&&audio.duration>0?audio.currentTime/audio.duration:0;if(peaks){const count=Math.floor(w/3);for(let i=0;i<count;i++){const v=peaks[Math.min(peaks.length-1,Math.floor(i/count*peaks.length))],height=2+v*(h-4);g.fillStyle=i/count<=progress?'#d9b8ff':'#604e74';g.fillRect(i*3,(h-height)/2,1.4,height);}}else{g.fillStyle='#51405f';g.fillRect(0,h/2-1,w,2);g.fillStyle='#d9b8ff';g.fillRect(0,h/2-1,w*progress,2);}if(Number.isFinite(audio.duration)&&audio.duration>0){for(const marker of sessionControls?.markers||[]){const x=marker.time/audio.duration*w;g.fillStyle='#eebf82';g.beginPath();g.moveTo(x-3,0);g.lineTo(x+3,0);g.lineTo(x,5);g.fill();}}if(loopA!==null&&Number.isFinite(audio.duration)){g.fillStyle='#65d5df';g.fillRect(loopA/audio.duration*w,0,1,h);if(loopB!==null){g.fillRect(loopB/audio.duration*w,0,1,h);g.fillStyle='#65d5df19';g.fillRect(loopA/audio.duration*w,0,(loopB-loopA)/audio.duration*w,h);}}}
new ResizeObserver(drawWave).observe($('.wave-track'));
function syncLoop(){const active=loopA!==null&&loopB!==null;$('#loop-a').textContent=loopA===null?'Set A':`A · ${fmt(loopA)}`;$('#loop-b').textContent=loopB===null?'Set B':`B · ${fmt(loopB)}`;$('#loop-status').textContent=active?`Looping ${fmt(loopA)} – ${fmt(loopB)}`:loopA!==null?'Move forward, then set B.':'No passage selected';drawWave();}
$('#loop-a').onclick=()=>{if(!current||!Number.isFinite(audio.duration)){toast('Start a song first.');return;}loopA=audio.currentTime;loopB=null;syncLoop();};$('#loop-b').onclick=()=>{if(loopA===null){toast('Set the start of your passage first.');return;}if(audio.currentTime<=loopA+.5){toast('Set B at least half a second after A.');return;}loopB=audio.currentTime;seekTo(loopA);syncLoop();};$('#loop-clear').onclick=()=>{loopA=loopB=null;syncLoop();};
$('#play').onclick=togglePlay;$('#previous').onclick=previous;$('#next').onclick=()=>goNext();$('#shuffle').onclick=()=>{shuffle=!shuffle;shufflePlayed.clear();if(current)shufflePlayed.add(current.id);$('#shuffle').setAttribute('aria-pressed',shuffle);toast(shuffle?'Shuffle is on.':'Shuffle is off.');};$('#repeat').onclick=()=>{repeat=(repeat+1)%3;$('#repeat').setAttribute('aria-pressed',repeat>0);$('#repeat').setAttribute('aria-label',['Repeat off','Repeat session','Repeat song'][repeat]);$('#repeat-one').hidden=repeat!==2;toast(['Repeat is off.','Your session will repeat.','This song will repeat.'][repeat]);};
$('#mute').onclick=()=>{muted=!muted;updateGain();sync();};$('#volume').oninput=e=>{volume=Number(e.target.value);muted=false;updateGain();persist('volume');sync();};$('#sound-mute').onclick=()=>$('#mute').click();$('#sound-volume').oninput=e=>{volume=Number(e.target.value);muted=false;updateGain();persist('volume');sync();};$('#seek').oninput=e=>{seekTo(Number(e.target.value)/1000*audio.duration);};$('#speed').oninput=e=>{audio.playbackRate=Number(e.target.value);audio.preservesPitch=true;$('#speed-value').value=`${Number(e.target.value)}×`;};
$('#favorite').onclick=()=>{if(!current)return;const saved=storage.get('pmp.saved',[]),i=saved.findIndex(t=>t.id===current.id);if(i<0)saved.unshift({id:current.id,savedAt:Date.now()});else saved.splice(i,1);if(storage.set('pmp.saved',saved)){syncFavorite();toast(i<0?'Saved to your library.':'Removed from saved songs.');}else toast('Your browser couldn’t save this change.');};
$$('.import-trigger').forEach(b=>b.onclick=()=>$('#audio-files').click());$('#audio-files').onchange=e=>importFiles(e.target.files);
$('#queue-list').onclick=e=>{const button=e.target.closest('button'),li=button?.closest('li');if(!li)return;const index=queue.findIndex(t=>t.id===li.dataset.id),track=queue[index];if(!track)return;const action=button.dataset.action;if(action==='select'){select(track);return;}if(action==='up'&&index>0)[queue[index-1],queue[index]]=[queue[index],queue[index-1]];if(action==='down'&&index<queue.length-1)[queue[index+1],queue[index]]=[queue[index],queue[index+1]];if(action==='remove'){const playing=!audio.paused;queue.splice(index,1);if(current?.id===track.id){const next=queue[Math.min(index,queue.length-1)];if(next)select(next,{play:playing});else clearCurrent();}toast('Removed from this queue. Your saved audio is still on this device.');}renderQueue();persist('session');};
$('#restore-library').onclick=()=>{const missing=available.filter(t=>!queue.some(q=>q.id===t.id));queue.push(...missing);renderQueue();persist('session');toast(`${missing.length} saved ${missing.length===1?'song is':'songs are'} back in your session.`);};
$('#clear-queue').onclick=()=>{queue.splice(0);clearCurrent();toast('Queue cleared. Your saved audio is still on this device.');};
function closePanel(){if(!currentPanel)return;if(currentPanel.id==='visual-panel')visualStudio?.close();currentPanel.hidden=true;currentPanel=null;$('#panel-backdrop').hidden=true;document.body.style.overflow='';$$('.topbar,.room,#transport').forEach(el=>el.inert=false);$$('[aria-controls$="-panel"]').forEach(b=>b.setAttribute('aria-expanded','false'));returnFocus?.focus();}
function syncMotion(){room?.setMotion(visualState.motion);$('#motion').checked=visualState.motion;$('#motion-enable').hidden=visualState.motion;$('#motion-note').textContent=visualState.motionPreference==='system'?(reduced.matches?'Your device prefers reduced motion. Turn Motion on to animate your music.':'Motion follows your device settings until you choose.'):(visualState.motion?'Motion is on. Your choice stays on when you return.':'Motion is off. Your choice stays off when you return.');sync();}
function chooseMotion(enabled){visualState.motionPreference=enabled?'on':'off';visualState.motion=enabled;syncMotion();persist('motionPreference');}
function openPanel(id){if(currentPanel?.id===id){closePanel();return;}const opener=document.activeElement;closePanel();returnFocus=opener;currentPanel=$('#'+id);currentPanel.hidden=false;$('#panel-backdrop').hidden=false;document.body.style.overflow='hidden';$$('.topbar,.room,#transport').forEach(el=>el.inert=true);$$(`[aria-controls="${id}"]`).forEach(button=>button.setAttribute('aria-expanded','true'));if(id==='visual-panel')visualStudio?.open();currentPanel.querySelector('button')?.focus();}
$('#queue-search').oninput=renderQueue;$('#session-toggle').onclick=()=>openPanel('session-panel');
const sceneSelection=createSceneSelection({getCurrent:()=>visualState.model,onSelect(id){manualScene=getScene(id).id;performanceDirector?.bypass();visualState.model=manualScene;room?.setModel(visualState.model);persist('model');visualStudio?.refreshScene();},open:()=>{openPanel('visual-panel');visualStudio?.showTab('scene');},close:()=>visualStudio?.refreshScene()});
$('#queue-toggle').onclick=()=>openPanel('queue-panel');$('#sound-toggle').onclick=()=>openPanel('sound-panel');$('#visual-toggle').onclick=()=>openPanel('visual-panel');$('#help-toggle').onclick=()=>openPanel('help-panel');$$('.close-panel').forEach(b=>b.onclick=closePanel);$('#panel-backdrop').onclick=closePanel;
function setWorld(id,{save=true}={}){const selected=getWorld(id),world=selected.id;visualState.world=world;document.documentElement.style.setProperty('--accent',selected.accent);document.documentElement.style.setProperty('--accent-rgb',colorRGB(selected.accent));$$('[data-world]').forEach(b=>{b.classList.toggle('active',b.dataset.world===world);b.setAttribute('aria-pressed',b.dataset.world===world);});$('#world-name').textContent=selected.name.toUpperCase();$('.stage-index').textContent=String(WORLDS.indexOf(selected)+1).padStart(2,'0');$('.fallback-art').style.cssText=worldStyle(world);$('#selected-world').textContent='Now in '+selected.name;room?.setWorld(world);sync();if(save)persist('world');}
$('#world-grid').innerHTML=WORLDS.map(w=>`<button class="world-card" data-world="${w.id}" aria-pressed="false"><span class="world-art" style="${worldStyle(w.id)}"></span><span class="world-card-copy"><strong>${w.name}</strong><small>${w.mood}</small></span><span class="world-selected" aria-hidden="true">✓</span></button>`).join('');
$('#worlds-toggle').onclick=()=>openPanel('worlds-panel');
$('#spin').checked=visualState.spin;$('#spin').onchange=e=>{visualState.spin=e.target.checked;room?.setSpin(visualState.spin,visualState.rpm);persist('spin');};$('#spin-rpm').value=visualState.rpm;$('#spin-rpm-value').value=visualState.rpm+' RPM';$('#spin-rpm').oninput=e=>{visualState.rpm=Number(e.target.value);$('#spin-rpm-value').value=visualState.rpm+' RPM';room?.setSpin(visualState.spin,visualState.rpm);persist('rpm');};
$('#auto-orbit').checked=visualState.autoOrbit;$('#auto-orbit').onchange=e=>{visualState.autoOrbit=e.target.checked;room?.setAutoOrbit(visualState.autoOrbit);persist('autoOrbit');};$('#reactivity').value=visualState.reactivity;$('#reactivity-value').value=Math.round(visualState.reactivity*100)+'%';$('#reactivity').oninput=e=>{visualState.reactivity=Number(e.target.value);$('#reactivity-value').value=Math.round(visualState.reactivity*100)+'%';room?.setReactivity(visualState.reactivity);persist('reactivity');};

$$('[data-world]').forEach(b=>b.onclick=()=>setWorld(b.dataset.world));$('#form').value=visualState.form;$('#form').onchange=e=>{visualState.form=e.target.value;room?.setForm(e.target.value);persist('form');};$('#intensity').value=visualState.intensity;$('#intensity-value').value=Math.round(visualState.intensity*100)+'%';$('#intensity').oninput=e=>{visualState.intensity=Number(e.target.value);room?.setIntensity(visualState.intensity);$('#intensity-value').value=Math.round(visualState.intensity*100)+'%';persist('intensity');};syncMotion();$('#motion').onchange=e=>chooseMotion(e.target.checked);$('#motion-enable').onclick=()=>{chooseMotion(true);$('#visual-toggle').focus();};reduced.addEventListener('change',()=>{if(visualState.motionPreference==='system'){visualState.motion=motionEnabled('system',reduced.matches);syncMotion();}});$('#quality').value=visualState.quality;$('#quality').onchange=e=>{visualState.quality=e.target.value;room?.setQuality(e.target.value);persist('quality');};$('#reset-camera').onclick=()=>room?.reset();
visualStudio=createVisualStudio({store:visualStore,getRoom:()=>room,getModel:()=>visualState.model,toast,audio,togglePlay,onManualEdit:()=>performanceDirector?.bypass(),onCompareChange:value=>performanceDirector?.setComparing(value)});
performanceDirector=createPerformanceDirector({container:$('#studio-view-director'),storage,getRoom:()=>room,getBase:()=>visualStudio.settings,getScene:()=>visualState.model,getManualScene:()=>manualScene,getTrack:()=>current?{id:current.id,title:current.title}:null,audio,seek:seekTo,toast,onActivate:()=>visualStudio.endCompare(),onScene(id){visualState.model=getScene(id).id;room?.setModel(visualState.model);sceneSelection.synchronize();visualStudio.refreshScene();}});
function cinema(force){const enabled=force??!document.body.classList.contains('cinema');document.body.classList.toggle('cinema',enabled);$('#cinema').setAttribute('aria-pressed',enabled);$('#cinema').setAttribute('aria-label',enabled?'Exit cinema mode':'Enter cinema mode');$('#cinema-label').textContent=enabled?'Exit cinema':'Cinema mode';setTimeout(()=>room?.reset(),50);}$('#cinema').onclick=()=>cinema();
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else{cinema(true);toast('Cinema mode is ready. Full screen isn’t available in this browser.');}}catch{cinema(true);toast('Cinema mode is ready. Your browser didn’t allow full screen.');}}$('#fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',()=>$('#fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit full screen':'Enter full screen'));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(currentPanel)closePanel();else cinema(false);return;}if(currentPanel){if(e.key==='Tab'){const focusable=[...currentPanel.querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(!currentPanel.contains(document.activeElement)){e.preventDefault();(e.shiftKey?last:first)?.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,button,a,[contenteditable="true"]'))return;const key=e.key.toLowerCase();if([' ','arrowleft','arrowright','m','c','f','q','b'].includes(key))e.preventDefault();if(key===' ')togglePlay();if(key==='m')$('#mute').click();if(key==='c')cinema();if(key==='f')fullscreen();if(key==='q')openPanel('queue-panel');if(key==='b')sessionControls?.addBookmark();if(key==='arrowleft'){if(e.shiftKey)previous();else if(current)seekTo(audio.currentTime-5);}if(key==='arrowright'){if(e.shiftKey)goNext();else if(current)seekTo(audio.currentTime+5);}});
let dragDepth=0;document.addEventListener('dragenter',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();dragDepth++;$('#drop-zone').hidden=false;}});document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}});document.addEventListener('dragleave',e=>{if(e.dataTransfer?.types.includes('Files')){dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('#drop-zone').hidden=true;}});document.addEventListener('drop',e=>{if(e.dataTransfer?.files.length){e.preventDefault();dragDepth=0;$('#drop-zone').hidden=true;importFiles(e.dataTransfer.files);}});
for(const event of ['play','pause','loadedmetadata','durationchange','timeupdate','ended','volumechange'])audio.addEventListener(event,()=>{sync();if(['play','pause','ended'].includes(event)){renderQueue();if('mediaSession'in navigator)navigator.mediaSession.playbackState=audio.paused?'paused':'playing';}if(event==='pause'||event==='ended'){clearTimeout(saveTimer);saveTimer=null;persist();}if(event==='timeupdate'){if(loopA!==null&&loopB!==null&&audio.currentTime>=loopB)audio.currentTime=loopA;if(!saveTimer)saveTimer=setTimeout(()=>{saveTimer=null;persist();},1000);}});
audio.addEventListener('waiting',()=>{if(current)$('#stage-status').textContent='LOADING YOUR SOUND';});audio.addEventListener('playing',sync);audio.addEventListener('error',()=>{if(current){$('#stage-status').textContent='TRY ANOTHER AUDIO FILE';toast('This audio couldn’t play. Try a supported file, or a library URL that allows audio access.');}});audio.addEventListener('ended',()=>{if(sessionControls?.shouldStopAtEnd())return;if(loopA!==null&&loopB!==null){audio.currentTime=loopA;togglePlay({claim:false});return;}if(repeat===2){audio.currentTime=0;togglePlay({claim:false});}else goNext(true);});
window.addEventListener('pagehide',()=>{persist();audio.pause();});window.addEventListener('storage',e=>{if(e.key==='pmp.saved')syncFavorite();if(e.key==='pmp.room.preferences.v2'){const latest=roomStore.readPreferences(),preference=motionPreference(latest);if(preference!==visualState.motionPreference){visualState.motionPreference=preference;visualState.motion=motionEnabled(preference,reduced.matches);syncMotion();}if(['record','aurora','orbital','liquid'].includes(latest.model)&&latest.model!==manualScene){manualScene=latest.model;performanceDirector?.bypass();visualState.model=latest.model;room?.setModel(visualState.model);sceneSelection?.synchronize();visualStudio?.refreshScene();}}});
if('mediaSession'in navigator)for(const[name,fn]of Object.entries({play:()=>{if(audio.paused)togglePlay();},pause:()=>audio.pause(),previoustrack:previous,nexttrack:()=>goNext(),seekto:d=>{seekTo(d.seekTime);},seekbackward:d=>seekTo(audio.currentTime-(d.seekOffset||5)),seekforward:d=>{seekTo(audio.currentTime+(d.seekOffset||5));}}))try{navigator.mediaSession.setActionHandler(name,fn);}catch{}
function analyse(){const measured=soundControls.read(performance.now());if(measured)bins=measured;room?.setAudio(bins,ctx?.sampleRate||48000,analyser?.fftSize||2048,!audio.paused&&!audio.ended&&audio.readyState>=3,!muted&&volume>0);performanceDirector?.tick(performance.now());requestAnimationFrame(analyse);}requestAnimationFrame(analyse);
window.PMP_PLAYER={ready,get state(){return{current:current?.id,queue:queue.map(t=>({id:t.id,title:t.title,local:t.local})),paused:audio.paused,time:audio.currentTime,duration:audio.duration,volume,muted,repeat,shuffle,eq:soundControls.state.settings.eq,sound:soundControls.state,session:sessionControls?.state,loopA,loopB,waveform:peaks?.length||0,context:ctx?.state,restoring,visual:{...visualState,studio:visualStudio?.settings,director:performanceDirector?.live}};}};
updateGain();setWorld(visualState.world,{save:false});sync();


