import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../public/consent.js',import.meta.url),'utf8');
const config=()=>({enabled:true,cmpId:300,googleVendorId:755,scriptUrl:'https://fundingchoicesmessages.google.com/i/pub-1234567890123456?ers=1',timeoutMs:1000});
function tc(overrides={}){return {cmpId:300,cmpStatus:'loaded',eventStatus:'tcloaded',gdprApplies:true,isServiceSpecific:true,tcString:'TEST-ONLY-CONSENT-STRING-NOT-A-REAL-GRANT.disclosure',listenerId:17,purpose:{consents:{1:true,3:true,4:true},legitimateInterests:{2:true,7:true,9:true,10:true}},vendor:{consents:{755:true},legitimateInterests:{755:true},disclosedVendors:{755:true}},publisher:{restrictions:{}},...overrides};}
function fixture(t,{withApi=true}={}){
  const scripts=[],calls=[],listeners=new Map();let callback;
  const document={querySelector:()=>({nonce:'document-nonce'}),createElement:()=>({remove(){this.removed=true}}),head:{appendChild:script=>scripts.push(script)}};
  const window={document,setTimeout,clearTimeout,addEventListener:(name,fn)=>listeners.set(name,fn)};
  if(withApi)window.__tcfapi=(name,version,cb,arg)=>{calls.push({name,version,arg});if(name==='addEventListener')callback=cb;};
  vm.runInNewContext(source,{window,URL,console});
  const api=window.PMPConsent;t.after(()=>api.destroy());
  return {api,window,scripts,calls,listeners,accept:(data,success=true)=>callback(data,success)};
}
test('default performs no SDK/CMP load and grants nothing',async t=>{const f=fixture(t);assert.equal(f.scripts.length,0);f.api.start({enabled:false});assert.equal(f.scripts.length,0);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);});
test('explicit CMP starts without blocking page and propagates nonce',t=>{const f=fixture(t);const state=f.api.start(config(),{nonce:'explicit-nonce'});assert.equal(state.phase,'waiting-for-cmp');assert.equal(f.scripts.length,1);assert.equal(f.scripts[0].nonce,'explicit-nonce');assert.deepEqual(f.calls.map(call=>call.name),['ping','addEventListener']);});
test('real observer path evaluates personalized and forwards current string',async t=>{const f=fixture(t);f.api.start(config());f.accept(tc());const decision=await f.api.getDecision({purpose:'audio'});assert.equal(decision.allowed,true);assert.equal(decision.personalized,true);assert.equal(decision.storageAllowed,true);assert.equal(decision.requestParams.gdpr,'1');assert.equal(decision.requestParams.gdpr_consent,tc().tcString);});
test('storage consent is required even for non-personalized ads',async t=>{const f=fixture(t);f.api.start(config());const data=tc();data.purpose.consents={1:true};f.accept(data);assert.equal((await f.api.getDecision({purpose:'banner'})).personalized,false);data.purpose.consents[1]=false;f.accept(data);const decision=await f.api.getDecision({purpose:'banner'});assert.equal(decision.allowed,false);assert.equal(decision.reason,'device-storage-not-permitted');});
test('failed, loading, unknown applicability and UI shown callbacks cannot grant',async t=>{const f=fixture(t);f.api.start(config());for(const patch of [{cmpStatus:'loading'},{eventStatus:'cmpuishown'},{gdprApplies:undefined},{cmpId:12}]){f.accept(tc(patch));assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);}f.accept(tc(),false);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);});
test('Google disclosure, vendor consent and basic ads legal bases checked',async t=>{const f=fixture(t);f.api.start(config());for(const change of [d=>d.vendor.disclosedVendors={},d=>d.vendor.consents[755]=false,d=>d.vendor.legitimateInterests[755]=false,d=>d.purpose.legitimateInterests[7]=false,d=>d.isServiceSpecific=false]){const data=tc();change(data);f.accept(data);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);}});
test('publisher restrictions are honored and do not expand Google legal basis',async t=>{const f=fixture(t);f.api.start(config());let data=tc();data.publisher.restrictions={2:{755:0}};f.accept(data);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);data.publisher.restrictions[2][755]=1;f.accept(data);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);data.purpose.consents[2]=true;f.accept(data);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,true);data.publisher.restrictions[1]={755:2};f.accept(data);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);});
test('withdrawal notifies consumer and removes prior permission',async t=>{const f=fixture(t),events=[];f.api.subscribe(value=>events.push(value));f.api.start(config());f.accept(tc());const count=events.length;const data=tc({eventStatus:'useractioncomplete'});data.purpose.consents[1]=false;f.accept(data);assert.ok(events.length>count);assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);assert.equal(events.some(event=>'tcString' in event),false);});
test('outside TCF has no geographic default permission or DOM-event path',async t=>{const f=fixture(t);f.api.start(config());f.accept(tc({gdprApplies:false}));assert.equal((await f.api.getDecision({purpose:'audio'})).reason,'non-tcf-adapter-required');assert.deepEqual([...f.listeners.keys()],['pagehide']);});
test('configured direct provider adapter must provide complete current CMP decision',async t=>{const f=fixture(t);const decision={source:'cmp',cmpId:300,scope:'non-tcf',ready:true,allowed:true,storageAllowed:true,personalized:false,restrictDataProcessing:true,requestParams:{gpp:'DBABMA',gpp_sid:'7'}};let update;const adapter={id:'provider.us',subscribe:fn=>{update=fn;return()=>{}},read:async()=>decision};f.api.start({...config(),nonTcfAdapterId:'provider.us'},{nonTcfAdapter:adapter});f.accept(tc({gdprApplies:false}));assert.equal((await f.api.getDecision({purpose:'banner'})).allowed,true);decision.storageAllowed=false;update();assert.equal((await f.api.getDecision({purpose:'banner'})).allowed,false);});
test('unregistered adapter, unsupported params and missing subscription fail closed',async t=>{for(const variant of ['wrong-id','no-unsubscribe','bad-param']){const f=fixture(t);const adapter={id:variant==='wrong-id'?'other':'provider.us',subscribe:()=>variant==='no-unsubscribe'?undefined:()=>{},read:async()=>({source:'cmp',cmpId:300,scope:'non-tcf',ready:true,allowed:true,storageAllowed:true,personalized:false,restrictDataProcessing:true,requestParams:{gdpr:'0'}})};f.api.start({...config(),nonTcfAdapterId:'provider.us'},{nonTcfAdapter:adapter});f.accept(tc({gdprApplies:false}));assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);}});
test('late adapter result after withdrawal cannot permit an ad',async t=>{const f=fixture(t);let resolve,change;const adapter={id:'provider.us',subscribe:fn=>{change=fn;return()=>{}},read:()=>new Promise(done=>resolve=done)};f.api.start({...config(),nonTcfAdapterId:'provider.us'},{nonTcfAdapter:adapter});f.accept(tc({gdprApplies:false}));const result=f.api.getDecision({purpose:'audio'});change();resolve({source:'cmp',cmpId:300,scope:'non-tcf',ready:true,allowed:true,storageAllowed:true,personalized:false,restrictDataProcessing:false});assert.equal((await result).allowed,false);});
test('CMP stub replacement binds loaded API; later unrelated replacement revokes',async t=>{const f=fixture(t);f.api.start(config());f.window.__tcfapi=()=>{};f.accept(tc());assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,true);f.window.__tcfapi=()=>{};assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);});
test('restart removes listener and ignores old callback',async t=>{const f=fixture(t);f.api.start(config());f.accept(tc());f.api.start({enabled:false});assert.ok(f.calls.some(call=>call.name==='removeEventListener'&&call.arg===17));f.accept(tc());assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);assert.equal(f.scripts[0].removed,true);});
test('Google revocation uses the documented callbackQueue, not an ad consent grant',async t=>{const f=fixture(t);f.window.googlefc={callbackQueue:[]};f.api.start(config());f.accept(tc());assert.equal(f.api.openPreferences(),true);assert.equal(typeof f.window.googlefc.callbackQueue[0].CONSENT_API_READY,'function');assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);});
test('already loaded matching CMP is observed without loading its script twice',async t=>{const f=fixture(t);const original=f.window.__tcfapi;f.window.__tcfapi=(command,version,callback,arg)=>command==='ping'?callback({cmpLoaded:true,cmpId:300}):original(command,version,callback,arg);f.api.start(config());assert.equal(f.scripts.length,0);f.accept(tc());assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,true);});
test('missing CMP times out without permitting ads or repeated indefinite loading',async t=>{const f=fixture(t,{withApi:false});f.api.start(config());await new Promise(resolve=>setTimeout(resolve,1100));assert.equal(f.api.getState().phase,'cmp-unavailable');assert.equal((await f.api.getDecision({purpose:'audio'})).allowed,false);assert.equal(f.scripts.length,1);});
