/**
 * record-memory.mjs — append this deploy's records to the project memory tier (DECISIONS.md, infra.md, STATE.md),
 * append-only, UTF-8, read-then-append in one process so no peer lane's bytes are overwritten (rule 13).
 * Every number below was measured in this session; the sources are named inline.
 */
import {appendFileSync, readFileSync} from 'node:fs';
import {resolve} from 'node:path';

const memory = resolve(import.meta.dirname, '..', '.claude', 'memory');
const append = (file, text) => { const path = resolve(memory, file); const before = readFileSync(path, 'utf8'); appendFileSync(path, (before.endsWith('\n') ? '' : '\n') + text, 'utf8'); return path; };

const decisions = `
D-PMP-21 - 2026-09-15 13:5x (+03): NEW WEBSITE DEPLOYED TO PRODUCTION (Berk 12:45 "basla ve mevcut geomagics_production profile daki playmusicpromopts sunucusuna kur"). https://www.playmusicprompts.com now serves website/ (Node 24 app on loopback 4177 behind the in-repo Node gateway on :80) on i-0c52f530769d1ac88; the old Next.js unit playmusicprompts.service is STOPPED and DISABLED, kept on disk under /opt/playmusicprompts (rollback: enable it, move the gateway back to 8080 - deploy-20260915/07-cutover.sh header). Evidence: host test suite 636/636 (deploy-20260915/03c-verify.sh, Node v24.13.1, ffmpeg 7.0.2), live HTTPS probe deploy-20260915/live-verify.mjs (8 pages 200, /api/connection available:true through real WIF + Secrets Manager + engine, /api/listen Range -> 206, direct IP -> 403 ORIGIN_UNVERIFIED), live real-browser account flow website/.state/verification/2026-09-15/live/accounts-report.json (register -> signed in, wrong password refused, change password, delete).
  DECISION (a) NO NGINX: the approved plan text said nginx, but infra.md records Berk's 2026-09-01 order "nginx istemiyorum"; the gateway was therefore written in Node (website/server/gateway.mjs + gateway-constants.mjs + gateway-main.mjs, test/gateway.test.mjs 7/7): verifies CloudFront X-Origin-Verify (timing-safe), resolves the viewer IP from CloudFront-Viewer-Address (origin request policy switched to Managed-AllViewerAndCloudFrontHeaders-2022-06 33f36d7e-..., ETag E1F83G8C2ARO7P -> E1PA6795UKMFR9, backup deploy-20260915/cf-www-config-before.json) with X-Forwarded-For last element as fallback, stamps X-PMP-Proxy-Secret / X-PMP-Client-IP, streams bodies. Veto path stated to Berk: nginx on request.
  DECISION (b) E-MAIL VERIFICATION OFF (Berk 12:41 "email verification olmadan yap simdilik"): PMP_ACCOUNT_EMAIL_VERIFICATION=off is the default (account-constants.mjs); production runs with NO mail transport (config.mail=null), /api/session identity.mail=false, the login page replaces "Forgot password?" with an honest note, request-reset answers 503 MAIL_NOT_CONFIGURED, register says "Account created - you are signed in". Switch back: PMP_MAIL_FROM + PMP_ACCOUNT_EMAIL_VERIFICATION=required once SES DKIM/production access exist.
  DECISION (c) LEGACY CATALOGUE THROUGH THE SITE'S OWN INGEST: 21 legacy jobs (23 public tracks in Postgres) inserted as status=ingesting with the engine's stored responseBody (deploy-20260915/import-legacy-catalogue.mjs); the app's own worker downloaded masters via the engine delivery-url endpoint and transcoded them (no generation, nothing billed). Result 21 tracks: job cmtnctbf60000ucxql2fhagy7 is partial because its takes 2 and 3 are "raw take (no render pass on variations)" with no delivered master, and the new site publishes only takes with a master (media.mjs takePlan) - the old site published the raw mp3s. Those 2 raw takes are NOT in the new catalogue by the site's own rule; Berk may order otherwise. Old Postgres rows and S3 media untouched.
  OBSERVED: within minutes of cutover, live visitors (or Berk) created songs on the new site - 4 ready + 1 pending jobs by 13:50 (+03), owner class visitor, prompt "A peaceful night drive..." with adaptive continuation (3 generations per first click). These are user-initiated paid generations, not agent actions.
  FIXES RECORDED (root causes): PowerShell redirect writes UTF-16 (use Node writeFileSync); AWS CLI on Windows dies with 'charmap' on non-ASCII (PYTHONUTF8=1 in deploy-20260915/ssm-run.mjs); Istanbul Local Zone IMDS region eu-central-1-ist-1 breaks S3 endpoints (AWS_REGION=eu-central-1 exported in every host script); engine-timeout.test.mjs asserted server-side socket count synchronously (one tick late on Linux) - now polls to zero, bounded; host test run needs the project docs fixtures (verify bundle carries them).
  OPEN (owner-only or later): Squarespace DKIM CNAMEs + SES production access -> then mail/verification; Google OAuth client for the Google button; apex https://playmusicprompts.com fetch failed from this machine (Squarespace apex redirect is his DNS plan, recorded 2026-09-02); CloudFront default behaviour is CachingDisabled (static assets uncached at the edge - a caching policy is a separate decision); SG still allows 0.0.0.0/0:80 but the gateway now answers 403 without the CDN secret.
`;

const infra = `
## Web host v3 - website/ (Node 24) behind the in-repo Node gateway (2026-09-15, D-PMP-21)

- Host unchanged: i-0c52f530769d1ac88 (geomagics_production 376210053952, eu-central-1-ist-1a), public IP 83.119.137.232. CloudFront E24H3DG0V4RCWB origin -> EC2 :80 (X-Origin-Verify custom header, unchanged value), default behaviour origin request policy = Managed-AllViewerAndCloudFrontHeaders-2022-06 (33f36d7e-f396-46d9-90e0-52428a34d9dc; was Managed-AllViewer 216adef6-...). /media/* -> S3 OAC unchanged.
- Runtime: /opt/node24 -> /opt/node-v24.13.1 (side-by-side; system /usr/bin/node stays v20.20.2), /opt/ffmpeg -> /opt/ffmpeg-static (johnvansickle 7.0.2 static, tar sha256 abda8d77ce8309141f83ab8edf0596834087c52467f6badf376a6a2a4c87cf67), user pmpweb (system, nologin), code /opt/pmp-website (root-owned; previous tree kept at /opt/pmp-website.prev by 08-redeploy.sh), state /var/lib/pmp-website (pmpweb 0700; website.sqlite + media/).
- Units: pmp-website.service (node server/main.mjs, EnvironmentFile /etc/pmp-website.env root 0600: NODE_ENV=production PORT=4177 PMP_ORIGIN PMP_STATE_DIR PMP_PROXY_SECRET PMP_CREDENTIAL_MODE=aws-wif PMP_API_KEY_SECRET_ID GOOGLE_APPLICATION_CREDENTIALS=/opt/playmusicprompts/website-wif-config.json AWS_REGION/AWS_DEFAULT_REGION=eu-central-1 PMP_FFMPEG PMP_FFPROBE PMP_ACCOUNT_EMAIL_VERIFICATION=off) and pmp-gateway.service (node server/gateway-main.mjs, /etc/pmp-gateway.env: PMP_GATEWAY_PORT=80 PMP_GATEWAY_BIND=0.0.0.0 PMP_PORT=4177 PMP_ORIGIN_VERIFY_SECRET PMP_PROXY_SECRET; CAP_NET_BIND_SERVICE). Old playmusicprompts.service disabled+stopped, files intact; Hydra + Postgres untouched.
- Secrets: engine tenant key moved to Secrets Manager playmusicprompts/website/engine-api-key (eu-central-1) from the old .env ON the host; EC2 role inline policy PmpWebsiteSecrets = GetSecretValue/DescribeSecret on secret:playmusicprompts/website/* only. PMP_PROXY_SECRET generated on host (64 chars). No secret value ever left the instance.
- Deploy tooling (repo): deploy-20260915/ - ssm-run.mjs (send script via SSM, --set placeholders, --resume, PYTHONUTF8), package.mjs (runtime + verify archives -> s3://playmusicprompts-deploy-376210053952/website|verify/), 02-prepare.sh, 03-install.sh, 03c-verify.sh (npm test on host, 636/636), 04-secrets.sh, 05-services.sh, 06b-import-legacy.sh + import-legacy-catalogue.mjs, 07-cutover.sh (rollback in header), 08-redeploy.sh (staging swap), live-verify.mjs, cf-inspect.mjs, cf-update-orp.mjs. Deploy key of the live tree: website/website-20260915T104812Z.tar.gz sha256 cccb1ce2ed29a7c7caae58df64426835e94e65bf6bb4eb4370d67d39d1608b24.
- Lessons: aws CLI on the host must be given --region eu-central-1 / AWS_REGION (IMDS says eu-central-1-ist-1); Windows AWS CLI needs PYTHONUTF8=1 when commands carry non-ASCII; PowerShell '>' redirection writes UTF-16 - never use it for JSON.
`;

const state = `
> ## 2026-09-15 13:5x (+03) - **NEW WEBSITE LIVE at https://www.playmusicprompts.com (D-PMP-21): website/ on Node 24 behind the in-repo Node gateway (:80) on i-0c52f530769d1ac88; old Next.js unit stopped+disabled (kept on disk).** Proven this session: host test suite 636/636; live HTTPS 8 pages 200, /api/connection available:true (real WIF + Secrets Manager + engine), audio Range 206, direct-IP 403; live real-browser account flow (register/sign-in/change/delete) passed; robots.txt + sitemap.xml 200. Legacy catalogue: 21 of 23 public tracks migrated through the site's own ingest (the 2 missing are raw, unmastered takes of one job - excluded by the site's own rule). E-mail verification OFF (Berk 12:41), no mail transport in production. Visitors already created 4+1 songs after cutover. OPEN (owner acts): SES DKIM CNAMEs + production access, Google OAuth client, apex DNS. NEXT: nothing running unattended; await Berk's review of the live site.
`;

console.log(JSON.stringify({decisions: append('DECISIONS.md', decisions), infra: append('infra.md', infra), state: append('STATE.md', state)}, null, 1));
